// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8a3PcNrLoX0Fxb1UkH85Dku04c2s/KIrto3vkWEeSN7nX45IwZM8MViDAAOBIk5Tu",
	"bz/VDfDNkeTNZnc/bJWrrCGBRqPR6HfztyjRWa4VKGej2W+RTdaQcfrzZF2oW/wjBZsYkTuhVTSLjlmC",
	"L5heMgf3jt0Jt2a5tgLfM6GW2mQc/x5HcZQbnYNxAggiqPQ6WXPTB3qy5oYnDkwTEtNGrITiMiy0BgNh",
	"cVCpZXtwn8jCig3sR3HktjlEs0goBysw0UMcibS/0CX8UoBKgKkiW4ChXaxLqHvTmB3E7DBm4/F4AGYc",
	"3Y9WehSeFkK5o0NcyDpu3N9pZwTLDu4Hx/YXuKrQT7RyoFw91zoj1Cp6eIgjA78UwkAazT4jXQKwFupx",
	"fT5fKhB68VdIHK5O7HCi1VKsBnZJzwtDB8+W2niUhFoxXBmss8xpdgUmEw7Y8fnpeK6u1sIyYRlnVmS5",
	"FEsBKW5iKVYEAg/mP6+uznE4G7FULJdgLFsandG7ZSElI7TAeATm6m4tkjUTKpFFCpblRm9ECoZZkJAQ",
	"clylLOHJGnFLmmiP56rHsRm/v6adWL/nJS+ki2avpnGHAB/4vciKrMFWfhru2oArDMKGe57lEvz8/vlm",
	"OgXZWidainvA09px5LgHmoXLFBbG7K1wazDsG5r4DZGRiAvM6VtQowW3SOQwOWbaMB5AKJ6BJy79tpPE",
	"k9ZOfsNXD5NxcwsVah1eiyO9ASN5fk0LPkW3Hyt6hWk57slPZQtwdwAqkPJpAlrIueFOmzYR54pOtkND",
	"vHjVBCIU7aiiTWuzAURvr46bFbjhrfb2ekWDm5LHbzOHcF3aOxzcolsbsGst09Zi0/GreOhGpiTqqjm0",
	"y48//vhzOGG2Nx1PRwfj6X5zZQLmpTges9S8IVI88iRShiXEhb/uiF77KiWV6PhfBpbRLPrTpFY9k6B3",
	"Jk0ps1vk4dk53SdaVIsUqdWKpTopMlCOuTV3TAGkdCEXwGwuhWNCOc1sxqUsj8COx+MnBShh9WU3BWyu",
	"lQXSeCVmv0Uoc+B6LVw0W3JpIY5KwfK5qRkP8NxRc03bemVaEqPaI4lAYazzmCPiD3EL1HcB1EEb1HfD",
	"sCwkWqUNYF8qkRQu+0NXPDb21D2jn9ZAksiALaRjd9wyC2YDqRcxNLMm9EJrCVzhCk1x27I7jOHbyuqo",
	"RIJwkNlncVVU8yxHWB2R21baLeHKE1dwKbcoYlO2l/FtUEZ+L0HDQcrEki25lAue3DKdJIUxkO4/R2p2",
	"GKzanccvbhB6kO2qq9U+Hp6L68IM7O/TxVlp+ZQqGbIFpKlQq0mlWfC8RAIt/NfO5bPJROqEy7W2bvZm",
	"+mYaNeRFYcSQoESSIGfmRmgj3LYlvj5HWql7NK8kj+JopXGXbYy/9/NZOZ9pg2odBZo/I6k5Yu/NUU3T",
	"uGQp4A6YzSFB88LY8Vy9I1Rn7CbgdINKsPwx8zNugk0W5gdMSXjc8MLpmzFqhJJ2zgiwDJT/n8w7RA4t",
	"jcJC86byDReSLySwsN5/+BXmKtHZQihvP5G0skWea+P8bNojrfniRSCFffGC7aWQI1W0YotCyJQ5vrL7",
	"s7kasZuVvmEjdl4YYO812uVgSBvscXnHt7ZGJWYn55+YVnIbMyv1HVi3TxDwUBAGaYyLQjmRAdsLfGrZ",
	"CBf785zOLv54cTWPYrbk1lXz7yXH6e/1h7Of2c9nxwNz7yWPfz47xqlX558mJ59+OJ6cnH/a9zv9gWhj",
	"X7zwOyLCsxE7LpwepeAgcWwBLaruhZPyCCRFShj8+JfTH06PGUJn788/+XfaQCYJXI7m0Yk28OEML3fy",
	"8TJQg677YksE8BBdXvgt6ZUERJntlYN+PjsOq/ox77RJoCKt39Bbf4+qHX321MPtEy38Hys9j74giCuz",
	"LfnEesZGEtRM6bxJ2wQ1wz1X8GYuL/wP/678Va1wbgDF2PvzTzFJLloOufwkkKkCS+TqzPa0IsQC+XiS",
	"gARvT89bJu/nGj1/0RG3KK4QCw/9X14CVKK9b3Z1xHjwfK4tJEUpXR7TB1y5pdyOVvpaigVfXtvEcDQ8",
	"r3UOCqXmiQd4GeDVBsktQH7NpdhA28ac9gzM/9R33ghxmuGs0uZCQYWqQrEMMm22jC/RO5TcOmQ4tvdR",
	"Sp7xEaLNnVhI2B/P1Qc/mRsgHkAPO/EqSQWAHoxDhZ6WjpheMqF44sRGuO14rj5ZEgZpw1EjUTiPXmXz",
	"iO29YplQhQO7j+d8sMZnB2ytC0MPpvhbwQZMWDZmwFeIvBe+iOhPa1DMAtlnfoY2TGfCOUjjkga4jYA2",
	"AZBbhhIPbZQiJ7nZXAV1roQVT7ZsAWu+Edrsj9vcFb3KhrSO1KuvZQWpV6sOJ4SjJ19QK9Lqyl2Xfm3b",
	"EH+GX1iBaAjlyknmEiVwOp6r4zQVQYtVb+8EXlFgvxRQQMqKHKmMeNGDayt+hfFcXXrqT0k7FkoKVFJp",
	"LRs7tHs56Ivy+2tP+2t/Zl+7zXDSJfP3uN6KrJCOK9CFlduScYh9CWG0Sg2g2ZPGpAIl4A0xkIBypSnm",
	"Vb+wDUY5u/jEUD4iYvvPIQb7qOSWwXKJwnQDqPgVq685QldajX4FozuEO9pFOL/F62zxPKIFiuwJxT58",
	"vx9cecI3bMrTcphGPM+NDmTaSSJ/40oiPYsqlSelGE83wiKGftFRsIcD3nNVWL5CdZSTntIqHAtyo6XL",
	"jAazgyzXhhuBxL5PAFK/kQ2XBTLtT9rcIvtrtbIiBdZjwOCiKxitDBfKh4qc0bLLztPvXu86mPqafC07",
	"N6NYBMXzyQ6Z0GDe+tTCtcV3y0LKmCm4q+HiqSG7vZoesUtveLNPqrZsSMtegDPb0TFJ+jXwFMzus/SL",
	"PcHnu/CfF9PpEbBph7YH092Bq2vrDHewKn2PSnydd2LARYbWAMn9KI4k/3UbxdFCFyqFtOHe1FK8fTbn",
	"YEZtkz8svKUQkhEp2DH7wHPbiGvRubk1CNObVStXpVEke7bMeE63EI8tkLBexwfRdFNMkD13umw8+XPQ",
	"l+UBzNq6ku3hHw21F7d03n4Pnj+S6YwhxTpQtGIpZFylcZgerAGRSiBbmliwDPSt0Rcv9zL3JzGPmlv3",
	"uyH5UloXtXre45bl3Di8FrmBGlsa31bcMYMNqK5MDVthe7lQqqkVCFeSPKQHLcvEPe7SUw5FCW0+CATh",
	"b5XlGbBc9wTBb9FiBSOK7oxAjTYH41fRrOK7ZK3V7TaaeQYcCmf5Va5TMRDV/55bYKkwkDgUjCiJuFB1",
	"xMAWi/KtQHYsPUVOrouwCbKqLTeyNDrzDsFv9aIPE++Sg7ETNLbflg56Fbyr3ZLWtCpsi7PakYzdkwwY",
	"Xs+6oF8D0+bqh4Yr/P8nY+c3NinHoeW3EZxtRA5mf4wsjNfKgovJDyI/1Y2E6kRbSdWUwq5r3PXWGbL1",
	"Aiv2z+pMWFdZJLU0CONbnD1oel+twcKA5SqyDFLBHcitZ/DykH0KJ2Z8owUdGPn+oyBcmeQOVFLJnYCR",
	"XetCoqp0yZq5tbZA16I6ogY3sD0Yr8ZokPcYfB4hxs+3aNheS5rgcl3z8PPANYqjRIp8tBGOEgqjHLE+",
	"Ovw6py3Q49qJDHThnvKnSp1MUQin2R0XjlQeL5UohYQ1Yu0gDjkg3FXQ1zgeJz/qBx1NrXdyDzL/v/d5",
	"NAtYxqxhRV+U6tIbNJS5QOEVxjZ0+kv2nju441t25d91WfxoOsjU9ug6MZCCcoJL+9Vu7VHtxjSgdKON",
	"ZZhwR2gRHeFzbtxgKti/9vqAgnGFdCLTKZd1RJHtUchWGyYyvqJkrVbwcUmR78f2cwX3ronAQ/z4+FME",
	"/+nirDXny0MckezcmZkQKi8GdneKj6sdOu03NGaXdWDOAATesSS/L4VaSfARan+IM3Yzj9YgpWZ32sh0",
	"Ht3gwHYw2w+1Mwq30GDPe2HGl/aUJs0t26spvo8AfpvTIc4j5GaE7kH5v/BZgP8Qs9ZQOhpkAz++8XOG",
	"A8Nf8yjljs/o7SRXq/+N1//1y3g8Hs+jhwfEtC07GluP0AZP1kKRL2dQWyLL1azQydT3aMn2Fjy5veMm",
	"ZQ0JPXBtHk8dBGrvhPZsCbZzmcYl6BxW6yLY/WfnL1qXoIPHl915jB/RNAqB/lJ/BD3YSPR21EtLLg3J",
	"/j5dTKES7tpOlTMF9DKgYSCjK4d3ailcQIgode+YBLVy64HUUEdqlakRf3uHZFe49YPZuEo42Wj2+fN0",
	"PD04PIpH0/H05avX8XQ8/fbNd19ifH549JKev3r9LT5/892XRlqsT51eiqy50E6GqUXlhmxGy/a0AkoM",
	"e0p5Wrf4pfrjqVRtX/M+MwvmzROKIqBor5D8WgbZcXANygyenjE+kd+hZ/m4jSuNZhlYy1fwJAoeyNCq",
	"pQoZUAf4hlHmzDCUguzTxWmvYGR3uq2exPZ2CtF2snB4mPjL9x8v7qb/9X6ln5Os3qXZh5Tljk2XQqzF",
	"BWzvYw7q+LRhLQdduN+jSqVNnhJ0FfkrLq0jBjWQL08m6PFtPDijJoD3+pvyoZPcDn7UwL2tojJJ170K",
	"ybWqAGnuM77zaL+tF8s8sHdDRxleVRcuEqkPKdSq4HJ08HVGdSXGH8Mauq7k85TBsCfQezYSb0a/uK/1",
	"BYL7+RjapuOV9nErwYw2h6Ps6GtQGErAIzpN1JrUHWIo7zXvNDOf0NGd3fXOpPbQe/K3s+1B51hnuRug",
	"7rnB6SoFA2mjXAbuXShdQ8hjRhVnUlDSwjLj70x55RncO8MTJ9RqrrhKmQcomgU4SwEytRMHWY7+r2UL",
	"WGoDLOFSVn4TqDTXQrmeB3qqnNFp4Qv4KOXRtiO9HPyBEg3hEVsWKuW4NpdU1PNV/PhLAWY7VD3KTbJm",
	"9JZ2bkDChqsEmE206erGLpqM57kUCfmc9tl60uNSn+FjrLdLlj3Be1lb01esOOiSJtrAACddtEgBDRPG",
	"Ix77QF0ojbDesGlZNF9ryOygV0BwiExdh3K4smxQ3fV02iOlaV2fcdBm7mi3Tk3Z44ptZwHaX8BYodVu",
	"RqAyEQq5DAQ1fQmJyMA6nuUtVj6cHr4cTQ9GB6+uDqazo+lsOv1/Q9taCXed6CwbKgl7L5A0+I6tuV23",
	"4PNFcnB49HIQpL7e+G0NgNTMhMKUckwT6kofjA9fjadDYHfCLMN4QwA3B+PpELjOMdVTG/SIm8RvbWvo",
	"JLuxnNLSqCM6/y7P/3d5/m5+2VHH0I+O+3HtUngSfVU422cjbY9fJGxA/t76ijMCQqe09a7574F2SUAG",
	"q5Ofh0grCI23pReHLgm2AbNAltkyT4e4EuUpLIoVRSZo+h33xf+lz1lLkzCgJ5qet8sWqpQfUVzuRFcX",
	"Li9c8NAYEXvMvimn+U6BREttxK8+tW61hJh981erVegjcKZIXIGG4v+5/PhjzL6RerXMnH/r2wtguRQJ",
	"mYm3sP0z5fZZzoWxMftGaZ2XHQkSlBs3SNZAHxeMqHRnmeEVwGltsjUGP0m6HSHwfqlskoC117ewvR6S",
	"S8c/XTI/BDfGTn9ohIFvYWsd2rJ2qxy/9zuExIBjUuvbIh+zd1xKW9XWHf90eX18cvL28vL6v97+3+vT",
	"HxiojTBakaW84UaQuyOq1Fm78WKrCzPyyIxuYTsSg/ZFaUsPyNijpstejiuTSt/YozHP+K9a8Ts7TnT2",
	"DdMGj7os+P1uOp36Y/wg1OnHdsSiOzmKo0yoMx/Smx0MmZNEqeua/sPEDwStz+D3HsDl25OLt1eNc/gb",
	"DsEv0jiLQXsZLCp53yPS39zHslTZ75LG+svkr1Uom9myRh7oq/Y+hDatMvIYDaBcWLi2Vj4Zzn2riEaX",
	"l2eTq7NLWvvyCGWH8oWptqp+mDGcTyOOf7qkWtOqxCnhsmalgaDvk5L8mdWb/Tvva+2uka3tUAeDcCBD",
	"8jiMZTiWEraT03NfkiSFumWpvqOKB0sZb8hyt41xDo0PZZsBAppFkDuWG7HhDhjCEUu2kDq5vQ4Pr0Xu",
	"2zJMAfvjti8c/gy3K0nVuP3k4LvD8XR8OP7KwFFJjJy79XOJgWNZbmAp7qGsz5Iwm0yoVMMe4V+fLs56",
	"RKE1mkQZs3eNyYUFxhdWy8JBGBuE0+STBWMnKXd8su8n+VVwyqJIbsFNPD7ljGw7Cs+LnA5o0qVnEyaK",
	"q96Er6Nj7xyfvEXf44xWgVnNGsxwtUJf+uDwW/Q8xtPJm5gdTBt/f3s4PnhNvw4OY4anf/D6jf/9OmYH",
	"r78bH756GX7vD3bclMxbZuKvfSdQG/OjfjtbyHLjuQuVio1ICy6rq8DwqvlQB5rUJcxm/eSUtIPI0AY4",
	"2FWzV2Fnxa9wvdg6aCN2MH355tW3r6c7i/hwHnJtCShUDvoCXOYBtmrcKngVctMnfA2h3OuXJcI+6pyK",
	"DFTtYAZkD6cv3+zCk+axO5G69WQNYrUm/HJxT4FlnzGsKoAN4LbazUUe+GMU7UtTfERmqO/QczwhiwFF",
	"HGpekrRR7NMa1PxjZ5PJSrh1sUB5EwzydDEJBTr9er3SjfC1pKHCRopbCKK/LoKm/jBTNSmGXtUPZ3X9",
	"61z96U/spzWnKGQA3GzECe2+ttQqZw3ovn+iwqBhAh2fn1L2/sWLusbqPajAvS9ezBhFdaiStc7s7p2c",
	"nZ7v92LpHhBNKGuvEMIlZFw5kdQZA8Kn2YxZdqCOiGHLPjIPryrIQlh1pM3AKMQdg+Kn8KRvuQuYvCvQ",
	"ZMdpP769iFkiubViGYKQMW1qFfa6gap6jawLlkuuFKRU9lXeairF5g6o0FgCR1ntWMkZnh3GQk9SndhJ",
	"pRarowOK336yMHR8CVfMFAqdbJVyqRVQf3JdbsgV8yzJEllYB4bO7YwOuyZl59BRRsG9A0NW1vlpqFQG",
	"lQggIvU54mbCc+GzIDe1hdyKB9LM6lTrnsTyLC6O37Nc5CCF8qs0T62M9JPozJBrIS1P75eCS+G2OOUE",
	"lDNckkcWTgZ9cbViPDHaWpYKVESLwkHKlE79QueoPZLtKDdQDm9dBMo+hjpNCXwDlqFZiCMMr5y8/XBk",
	"74Djz3CCf2JDV8Rzms+nIac1ubpV8Vh2f+6sc/SQjs9PCczzzqW8IT7kyXx7H+HxvVBoOVcluDE5ruVO",
	"PtR3OZjT4U57gD71WW2XAOJr1ihH/yvxBR7+yEvvWhrYnCcQIFEKv4kXJXKrfLBlezc7M8I3+3gH0Iry",
	"wELS9aQiCgL8ZMF2Sk2Co7938zdV+YR6nptAC7yvJ9xS4xrzhPHcGjNixJEnowFnBGy4jNlGWDQGrMiE",
	"5Ib42VO9JRm7jPOuln/VZer1K+6z/2hyWAMG+yHw2RaBHe+std1ZMOthnfivQyCMw5FviGJXV2dlnwb1",
	"4gbhGoQ04d5yMbvVrWWOZcmFrO5SJdWfu4fmxRrYSKOI10P87wLF06+VHjtut44h1/zih9SdImJZk7rB",
	"vzi9lSwkkRdyUmwvJAfXXKUSfQEBMq3yglrtU0ZPigRCVqI0MKRkF2jqWHYBvj+8Z23UOkXCilOs0Ann",
	"2/3r74lEjYh+tDngMl/zA/ochXcKo1l0NJ6Oj6I4qlwcf/LkGGo7FCnJpUCLHHc68KkAVljfJh2UQFuB",
	"d0oDSuvlQ2BazwHE8HWRdp/XfVVh7wMe9PkCV/c7+29n4OBPZa3yn6vSA3z8jltvwaTgw2fCOpGUaBBf",
	"faiuU99YqToeSiHTvNgj9uExWd/IYbdv2lffGBZuJv668EYOeZF0I5vNZSibD8texjFNAwrcVXUZC+3W",
	"5bdmkCyukbcrjyp06+Kvm5ubv1pUdL/NFWuVU+744gQJ0NgP9st4EasYw0e0NQ8gHFJcvmp9UgSHvJpO",
	"q5ftb6v4t9XL6msmHvB8rvBfhK8f5uqBdkH3sPLMTtPyYwdXPt8QvNDvdbotPQLwMcRG6npCIdrqY1HP",
	"+vhCWRXx0M52oD9MD7zyplt5OJ3+vdcO2VBafChfS2yZMltQJG9ZSEm+/Mu/Iya+nG0Ag1O14VKkZQAA",
	"1331j1k3mMTB7YIwMI5skWXcbEvWGJB/FlYZfTEMh3t7bLcUDXYi2FDc2LChQ+ygWWftZarsmPS2/FxU",
	"ZYwL2yjbDc4U2Yvf2LaZGAwhH0y9d7EvUUGHQKWWiZAh7deyNVy90h9CGA0TsC/SO13aj8rCZndP3YMS",
	"mhPQy/K78DMaXojTjOJwdWtgA5vS9xxRr00WDKsyGNYr1dqfseOEopHNyuhgjdT778IhK7k9FWkaQhQb",
	"wWvTNpCoZQL7Jq9G7TwRLBAZ0j+0kn6ox2d3df2zCuq9rfzHlNMPFFnu/05d2Gg/p3xC0mww5/TNk7Tw",
	"0gZd/2Dj0HEsJUWlfPPUBkEYSAuVcuXwTG7LC9H1xfBxlbGge4X2TFUls80D1wSG8p2t4ZsfDcGnEwdu",
	"ZJ0Bnt1U3p0FI9BH9onr0teLWaatY1U+cr8HDcXozYw8wrKgLciRxufQSFQ0XP6mXeD5GLmuWRPb465Z",
	"33poaP+BDq5gNZBYxEGfO2yP/NStLJtHX2oNP1cfBrtw+qz0OG6DPV5D+JH98eQ94Sxfa6cpjsMS7vDS",
	"DEz9fTcnFEeHC4Tgvzxi+pSqqfby/yAbqNWA9A+2gdptELj2rkvVhtnJUtBtG5W3DdJ+00LzM1ALGj5Q",
	"69KzQ2ral4HIfyFL7OX05R+/bmgD1WhgFCr9l7IAyxvSkILe6Ku/CrICN1QN6gqjLJkqlq58v/o8bnyH",
	"0pcNt+u7Kz+stJS8hdMPggxbVTj2v6voBmX0lbNszTfAbkbizQ2zxXIp7kt9GnxTv8jxrjp+tld2MJNK",
	"OZeFZVxtH8eq6fcGDRkiNc/YUieq8zbL3dbXJZRTytotH6pvGKEN+xNNzPBZieZ3dpLyIxU92XgmrPtQ",
	"1tn/YcKp04Sx63bYMrb4z5IN3/N/TQ/tbMgV8DfU881uv+zCJ4/oK7m74npV3KcudHea8VAB721DYt5d",
	"d/fExwUvyo4BIYUTwXSqewqywrrZXB2M2VsfMizXKxsH/K0ogyt2rg7H7IIwpstXtRXM1dGYXfoPBXb3",
	"VPZ9cstuwv5uqu9NpGDFynfJ22YjvwMJ1n/FJnySwqNMefqksE5n4ldodDxIvRJJ3zOsY2TP8Q07V76y",
	"nXvB2j0/67p6MaaP9nmXphXszelLb00QlURsR3yfCn11jNd270llHRKD+FGPdkFUE8KJNAzKea/t40OA",
	"dBYgzfxXilaFSNGd2ICxddwNAVBHSDmavWt0hMzYj1AYLpkCd+c/PWSAJndsRvpeZMV5Ifxaczs5DN1o",
	"d1x9OsYzy8iKFObqRorFpJp6w3Ke3FLKn75ZXYbOa1Z6ukWmLbG9UjkPbSJ/jCHb7nH6B1uynS6XAZEZ",
	"Nh8O6N+G5D9VUeHqR3/86vXHakoDp2h8N2tvyEza72hRD6LWetta33ld2mgWedTc7fSOxGxV9bzE5Sda",
	"RQbe3u03r4wHPFT3l6qZ5A+7WN22oQEqhyHNDpJ/jvHVcU9cSbs2ZjSMuNEOfFuikTcMPFtlHSc8F9HD",
	"l4f/CQAA//8jXw+XGWMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
