// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for GPUMode.
const (
	GPUModeAuto   GPUMode = "auto"
	GPUModeCoreml GPUMode = "coreml"
	GPUModeCuda   GPUMode = "cuda"
	GPUModeOff    GPUMode = "off"
	GPUModeTpu    GPUMode = "tpu"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl          string                             `json:"api_url"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`
	Gpu             GPUMode                            `json:"gpu,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// GPUMode GPU/accelerator mode. Configurable via TERMITE_GPU env var (viper auto-binding).
// - "auto": Auto-detect (default). TPU > CUDA/CoreML > CPU based on availability.
// - "tpu": Force TPU. Fails if TPU not available.
// - "cuda": Force CUDA. Fails if CUDA not available.
// - "coreml": Force CoreML (macOS only).
// - "off": CPU only, disable all GPU acceleration.
type GPUMode string

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8/XMbN7Lgv4KavSpLe8MPSbbj8Gp/UBzbT/fkWE+yNncXuihwpkkiwgATAEOJSen+",
	"9lfdwHwPJXmz2d0ftspVFmeARqPR3+ie36JEZ7lWoJyNZr9FNtlAxunPt5tC3eIfKdjEiNwJraJZdMoS",
	"fMH0ijm4d+xOuA3LtRX4ngm10ibj+Pc4iqPc6ByME0AQQaWLZMNNH+jbDTc8cWCakJg2Yi0Ul2GhDRgI",
	"i4NKLTuA+0QWVmzhMIojt8shmkVCOViDiR7iSKT9ha7glwJUAkwV2RIM7WJTQj2YxuwoZscxG4/HAzDj",
	"6H601qPwtBDKnRzjQtZx4/5OOyNYdnA/OLa/wOcK/UQrB8rVc60zQq2jh4c4MvBLIQyk0ewnpEsA1kI9",
	"rs/nSwVCL3+GxOHqxA5vtVqJ9cAu6Xlh6ODZShuPklBrhiuDdZY5zT6DyYQDdnpxNp6rzxthmbCMMyuy",
	"XIqVgBQ3sRJrAoEH8x+fP1/gcDZiqVitwFi2Mjqjd6tCSkZogfEIzNXdRiQbJlQiixQsy43eihQMsyAh",
	"IeS4SlnCkw3iljTRHs9Vj2Mzfr+gnVi/5xUvpItmr6ZxhwAf+b3IiqzBVn4a7tqAKwzChnue5RL8/P75",
	"ZjoF2VonWol7wNPac+S4B5qFyxQWxuydcBsw7AVNfEFkJOICc/oW1GjJLRI5TI6ZNowHEIpn4IlLv+0k",
	"8aS1k9/w1cNk3NxChVqH1+JIb8FIni9owafo9kNFrzAtxz35qWwJ7g5ABVI+TUALOTfcadMm4lzRyXZo",
	"iIJXTSBC0Y4q2rQ2G0D09uq4WYMb3mpvr59pcFPz+G3mEMSlvcPBLbqNAbvRMm0tNh2/iockMiVVV82h",
	"XX764Yf/E06YHUzH09HReHrYXJmAeS2Oxyw1b6gUjzyplGENcenFHdFri1JSqY7/YWAVzaI/TWrTMwl2",
	"Z9LUMvtVHp6d032iRbVKkVqtWaqTIgPlmNtwxxRASgK5BGZzKRwTymlmMy5leQR2PB4/qUAJqy/7KWBz",
	"rSyQxSsx+y1CnQOLjXDRbMWlhTgqFctPTct4hOeOlmvativTkhjVHkkFCmOdxxwRf4hboL4NoI7aoL4d",
	"hmUh0SptAPtSqaQg7A9d9djYU/eMftwAaSIDtpCO3XHLLJgtpF7F0Mya0EutJXCFKzTVbcvvMIbvKq+j",
	"UgnCQWafxVVRzbMcYXVUbttot5QrT1zBpdyhik3ZQcZ3wRj5vQQLBykTK7biUi55cst0khTGQHr4HK3Z",
	"YbBqdx6/uEHoQbarRKt9PDwXi8IM7O/68rz0fEqTDNkS0lSo9aSyLHheIoEW/hvn8tlkInXC5UZbN3sz",
	"fTONGvqiMGJIUQbfZGEhKYxwu6dOjCu3krvRWi+kWPLVwiaGo2lY6BwU7uutB3gV4NUqY50XtHcpP61I",
	"th5b5sPF9UedAvF6bTB44TSCugXIF1yKLbQNyrRnTf5D33mN4zTDWaWClZqnyBeKZZBps2N8ha6g5NYh",
	"M7GDT1LyjI8QNe7EUsLheK4++sncAENU0J1OPP+pANCDcSi9ael16RUTiidObIXbjefq2gL7oOv3/ohm",
	"bB69yuYRO3jFMqEKB/YwZvPoaIPPjthGF4YeTPG3gi2YsGzMgK8Rec2RTxDRHzegmAVSxn6GNkxnwjlI",
	"45IGuI2ANgGQO8ad93OLnNyx5iooYBLWPNmxJWz4Vmhz6D2zmglfZUMsJvX6a7lK6vW6w1SBi8jx04pE",
	"WLlF6cS2re4znMAKBEZGYMgeVx4xl1LfQTqeq9M0pdiAy/rtnZASTdUvBRSQsiJHKiNe9GBhxa8wnqsr",
	"T/0p2fZCSYHSnLKDgGWXdi8HHU9+v/C0X/gz+9pthpMumb/H9VZkhXRcgS6s3JWMQ+xLCKMJMoA6Lo1J",
	"K0lACTGQgHKl3vW6WNgGo5xfXjPYCnLsD59DDPZJyR2D1QqDgS1g5KVYLeYIXWk1+hWM7hDuZB/h/BYX",
	"2fJ5RAsUORCKffzuMPjthG/YlKflMI14nhsdyLSXRF7iSiI9iyqV26QYT7fCIoZ+0VEwfgHvuSosXwNL",
	"IacQXKtwLMiNloQZraODLNeGG4HEvk8AUr+RLZcFMu2P2twi+2u1tiIF1mPA4I8rGK0NF8rHhc5o2WXn",
	"6bev9x1MLSZfy87NkJWgeD7ZoxMazFufWhBbfIdhaswU3NVw8dSQ3V5NT9iVt7LsWvEtF5IvJficyiU4",
	"sxudkqbfAE/B7D9Lv9gTfL4P/3kxnZ4Am3ZoezTdH6UurDPcwbp0NCr1ddFJ+BQZ+jOk96M4kvzXXRRH",
	"S12oFNKGL1Nr8fbZXIAZeQYLVoeFhXcULxqRgh2zjzy3jSCWzs1tQJjerNq4Ko0q2bNlxnOSQjy2QMJ6",
	"HR8x66aamM3ViJ2tGk/+EuxleQCztq1kB/hHw+zFLZt32IPnj2Q6Y0ixDhStWAoZV2kcpgdvQKQSDjFQ",
	"JRYso/oNOt7lXub+JOZRc+t+N6RfSu+iNs8H3LKcG4dikRuosaXxbcMdM9iC6urUsBV2kAulmlaBcCXN",
	"Q3bQskzc4y495VCV0OaDQhBeqizPgOW6pwh+i5ZrGFEoNwI12h6NX0Wziu+SjVa3u2jmGXAodvWrLFIx",
	"kML7jltgqTCQOFSMqIm4UHV4YItl+VYgO5YuNfpuo1TYBFnVlhvBkIFIfvNbvejDxPvfYOzkho3Yu9Ib",
	"ryJ1DNsP+9OqHA3Oaoct+ycZMLyedUm/BqbN1feenUmg/v9k7PzGJuU49Py2grOtyMEcjpGFUawsuJhp",
	"VEDLQkg3EqqTWiFTUyq7rnPXW2fI1wus2D+rc2Fd5ZHU2iCMb3H2oOv9eQMWBjxXkWWQCu5A7jyDl4fs",
	"87Ux41st6MAoJB8F5cokd6CSSu8EjOxGFxJNpUs2zG20BRKL6oga3MAOYLweo0PeY/B5hBg/36NhBy1t",
	"gst13cOfBsQojhIp8tFWOMoejnLE+uQYtXcVfPcTY51AO9Bj4UQGunBPxVOlTcbheH53XDgyebw0opT/",
	"0Yi1gzgkfHFXwV7jeJz8aBx0MrXziIKfzP/vYx7NApYxa3jRl6W59A4NpSlReYWxDZv+kn3gDu74jn32",
	"77osfjIdZGp7skgMpKCc4NJ+dYR8UocxDSjd1EKZE9iTR8CY+oIbN3jv4197e4CHgU69yHTKZZ0+YAeU",
	"n9GGiYyv6WZGK3hGKP4Z7l0TgYf48fFnCP768rw158tDHJHu3JuGFCovBnZ3ho+rHTrtNzRmV0Wea4Ma",
	"cGMAAu9Y0t9XQq0l+HSUP8QZu5lHG5BSszttZDqPbnBgO3Plh9oZu/kpDPa8F2Z8aU9p0tyyg5rihwjg",
	"tzkd4jxCbkboHpT/C58F+A8xaw2lo0E28OMbP2c4MPw1j1Lu+IzeTnK1/l8o/q9fxuPxeB49PCCmbd3R",
	"2HqEPniyEYpiOYPWElmuZoXOtVyPluxgyZPbO25S1tDQA2LzeJ4wUHsvtGdrsL3LNISgc1gtQbCHz05W",
	"toSgg8eX/UnLH9A1Clm90n4EO9i41emYl5ZeGtL9fbqYQiXctYMqZwroXXeEgYxEDmVqJVxAiCh175gE",
	"tXabgTxwR2uVeVAvvUO6K0j9YOq9Uk42mv3003Q8PTo+iUfT8fTlq9fxdDz95s23X2J8fnzykp6/ev0N",
	"Pn/z7ZdGDrxPnV4+vLnQXoapVeWWfEbLDrQCugXylPK0bvFL9cdT9zJ9y/vMlLd3TyiLgKq9QvJrGWTP",
	"wTUoM3h6xvhbuw49y8dtXGk0y8BavoYnUfBAhlYts7+9BT5cXE94koAEfzuIuxiz6pIbQ3T0ez+/u/x4",
	"9vnd4sPFNQO1ZVtu2AE5w973XwpVZkpHbE5pZdSrpxQXgIPEtZIwF9dlKP72+vvTyVtt4ON59ejiug5F",
	"g/MspM/0InCXFwj7vTYJIKgxe88Fxk0rAox+edPlxilJkfJ6Dq7ZmIQ/h2dpA5lszPNoHmQ8+XRFbn+5",
	"X71a4TDEHB/HLBWWaMelZEizisTV7XuZMKAMfIybQvezSDn+RwujP7FaDaYOSo9gwLrjG0a3HoahUWPX",
	"l2e9y/79VyX1JHaw1ya2L3qGh4m/fvfp8m76nx/W+jkXjfsctSHfZ8+mS5vUEmp28CkHdXrWCH6Ca3PY",
	"o0rlHDxltyryV0qnTgDVQL48ebmKb+PBGTUBfBKnqe47F5MhLB5Qw1WSLelGy1ze8Z2ti0fm/rZuHh22",
	"3ZzyDs9nFUYZal4X9CJ5A1KodcHl6OjrYqTKKj+GNXQzA8+z7cOBXe/ZSLwZ/eK+NrQL2YTH0DadJEMf",
	"txLMaHs8yk6+BoWhy1NEp4lak7pDDOWTIHujhidcrs7uemdSJ1x65rSz7cFch85yN0DdC4PTVQoG0kap",
	"A9y7UHaEkMeMqoWkoDsoy4yXmVLkGdw7wxMn1HquuEqZByiaxRMrATK1EwdZLrkDy5aw0gZYwqWswmBQ",
	"aa6Fcr2EwplyRqeFL76iG6x2WOD14Pd0bxQesVWhUo5rc0kFGV/Fj78UYHZDlX/cJBtGb2nnBiRsuUqA",
	"2USbrqvTRZPxPJciIVtln+32eFzqM3yM9fbpsid4L2s7bhUrDmYY0IYOcNJlixTQ8Eg94rHPu2qDIQW3",
	"3k9tOahf65fuoVdAcIhM3fzAcFXQoLnr2bRHyoq6KYDBEKhj3Tr1QI8btr3FQ38FY4VW+xlhWQiZUgZt",
	"IEeN7ygXZR3P8hYrH0+PX46mR6OjV5+PprOT6Ww6/X9D21oLt0h0lg2V83wQSBp8xzbcblrw+TI5Oj55",
	"OQhSL7Z+WwMgNTOFogxfOaYJda2PxsevxtMhsHthllnZIYDbo/F0CFznmOqpDXrETeK3tjV0kt3UXOlp",
	"1Am6f5dW/7u0ej+/7ClL6V92+HHtMmZSfdXthL9ctj1+kbAF+XvLZc4JCJ3Szmdafg+0KwIyWFn6PERa",
	"dwooLb1rhZJgWzBLZJkd83SoA88UlsWaEk00/Y77wu0yhVBrkzCgp5qet8sWqnTdpbjci64uXF64EKEx",
	"IvaYvSin+SrvREttxK++UsJqCTF78bPVKtSAO1MkrkBH8X9fffohZi+kXq8y59/60nBYrURCbuIt7P5C",
	"pRos58LYmL1QWudlNbkE5cYNkjXQxwUjqsRaZSgCOK1NtsbgJ0m350ajX+aYJGDt4hZ2iyG9dPrjFfND",
	"cGPs7PtGVv8WdtahL2t3yvF7v0NIDDgmtb4t8jF7z6W0jEo6nWanP14tTt++fXd1tfjPd/93cfY9A7UV",
	"RivylLfcCAp3RHUT2i6a3+nCjDwyo1vYjcSgf1H60gM69qQZspfjyjvCF/ZkzDP+q1b8zo4Tnb1g2uBR",
	"l8Wa306nU3+MH4U6+9TOWHQnR3GUCXXuM7SzoyF3kii1qOk/TPxA0PoMfu8BXL17e/nuc+Mc/oZD8Is0",
	"zmLQXwaLRt7X9/c39ykPNXt+lzTWC5MXq1AFtWONa72v2vsQ2rTKyGM0gHJhYWGtfDI7/04Rja6uzief",
	"z69o7asT1B3K98nYKjU5YzifRpz+eBUzql4PFWsJlzUrDeTwn9Tkz6zr7cu8L51cIFvboepz4UCGWoAw",
	"luFYun+fnF34CjMp1C1L9R0VsFgqYIAsd7uYUpQE21fhBgjoFkHuWG7EljtgCEes2FLq5HYRHi5E7kvq",
	"TQGH43YsHP4M0pWkatx+cvTt8Xg6Ph5/ZeKoJEbO3ea5xMCxLDewEvdQlttJmE0mVHljT/Cv68vzHlFo",
	"jSZRxux9Y3JhgfGl1bJwEMYG5TS5tmDsJOWOTw79JL8KTlkWyS24icennJHtRuF5kdMBTbr0bMJEddWb",
	"8HV07J3jk1L0Hc5o1QvWrMEMV2uMpY+Ov8HIYzydvInZ0bTx9zfH46PX9OvoOGZ4+kev3/jfr2N29Prb",
	"8fGrl+H34WC3RMm8ZWHFwndxtDE/6bcihaIFPHehUrEVacFlJQoMRc2nOtClLmE2y2GnZB1Ehj7A0b4S",
	"zAo7K36FxXLnoI3Y0fTlm1ffvJ7urcnEeci1JaBQCOrrqZkH2CpZrOBVyE2fiDWEcq9flgj7rHMqMlB1",
	"gBmQPZ6+fLMPT5rH7kTqNpMNiPWG8MvFPSWW/QVwVdBtALfVbgzxwB+jaF+b4iNyQ313leMJeQyo4tDy",
	"kqaNYn+tQY0bdjaZrIXbFEvUN8EhT5eTUG/VL78swwhfGhwKpqS4haD665p26u0xVYNZ6DP8eF6XM8/V",
	"n/7EftxwykIGwFQBGNYIrZq2tCrnDegUCNcYNFyg04szKsb485/rkrkPoAL3/vnPM0ZZHSpMri/qD96e",
	"n10c9nLpHhBNKEvpEMIVZFw5kdQ3BoRPs5Gu7B4cEcOWPUAeXlVfh7DqTJuBUcg7BsNP6UnfLhUweV+g",
	"y47Tfnh3GbNEcmvFKiQhY9rUOux1C1UxInkXLJdcKUipiq+Uaqqs5w6oblwCR13tWMkZnh3GQk9SndhJ",
	"ZRarowPK315bGDq+hCtmCoVBtkq51Aqot7SuHuWKeZZkiSysA0Pndk6HXZOyc+ioo+DegSEv6+IsFJ6D",
	"SgQQkfoccTPhufC3IDe1h9zKB9LM6lTrfrLyLC5PP7Bc5CCF8qs0T63M9JPqzJBrIS1P75eCS+F2OOUt",
	"KGe4pIgsnAzG4mrNeGK0tSwVaIiWhYOUKZ36hS7QeiS7UW6gHN4SBLp9DGW3EvgWLEO3EEcYXgV5h+HI",
	"3gPHn+EE/8SGRMRzmr9PQ05rcnWrgLXs3NtbtuohnV6cEZjnnUspIT7liU5Bxh3h8Z1Q6DlX9+MxBa7l",
	"Tj7Wshzc6SDTHqC/+qy2SwDxNWt0F/xMfIGHP/Lau9YGNucJBEhUkdHEiy5yq/tgyw5u9t4I3xyiDKAX",
	"5YGFS9e3FVEQ4LUF26kcCoH+wc3fVLQVyrNuAi1QXt9yC4S9J4zn1pgRI448GQ04I2DLZcy2wqIzYEUm",
	"JDfEz57qLc3YZZz3tf6rhKm8Uq1qCA7Z/2xyWAMG+z7w2Q6Bne4tnd5b/+xhvfWd/QjjeOT729jnz+dl",
	"2w31UQblGpQ04d4KMbvFyuUdy4oLWclSpdWfu4emYA1spFGT7SH+V4Hq6dfKjp22OwGRa37xQ+rGH7Gq",
	"Sd3gX5zeuiwklRfupNhBuBzccJVKjAUEyLS6F9TqkG70pEgg3EqUDoaU7BJdHcsuwff29ryN2qZIWHPK",
	"FTrhfKt2/S2IqJHRj7ZHXOYbfkSfEvBBYTSLTsbT8UkUR1WI40+eAkNthzIluRTokeNOB9q8WWF9i2sw",
	"Am0D3ikNKL2Xj4FpPQcQw9c1931e90WivY8vUOu5q9yI8N0DHHxdlp7/pSo9wMfvufUeTAo+fSasE0mJ",
	"BvHVx0qc+s5KVTVUKpmmYI/Yx8d0feMOuy1pXy0xLEgm/rr0Tg5FkSSRzV5B1M3HZWvqmKYBJe6quoyl",
	"dpvyOyFIFte4tyuP6p13rPHXzc3NzxYN3W9zxVrVsXu+FkAKNPaD/TJexSrG8BFtzQMIhxSXr1qfg8Ah",
	"r6bT6mX7uxj+bfWy+hKFBzyfK/wX4euHuXqgXZAcVpHZWVo2qn/29w0hCv1Op7syIgCfQ2xcXU8oRVt9",
	"6OdZjfNlVcRD+7YD42F64I03SeXxdPr3XjvchtLiQ/e1xJYpswVl8laFlBTLv/w7YuKrEwcwOFNbLkVa",
	"JgBw3Vf/mHWDSxzCLggD48gWWcbNrmSNAf1nYZ3R155wuPfH9mvR4CeCDbWqDR865A6aZfNep8qOS2/L",
	"T/1UzriwjSrsEEyRv/jCtt3E4Aj5ZOq9i32JCgYEKrVMhBvSfi1bI9Qr4yGE0XAB+yq903T/qC5sNmvV",
	"LUWh1wSjLL8LP6MRhTjNKA9Xd3o2sCljzxG1TmXBsSqTYb1SrcMZO00oG9ksdA/eSL3/LhzykttTkaYh",
	"RbEVvHZtA4laLrDv2Wu0QhDBApEh/UMbI4ZatvY3SzyrP8L7yn9Md8RAkeXh77SFja8J0H1C0vxeAEJI",
	"IS28tsHQP/g4dBwrSVkp3wu3RRAG0kKlXDk8k9tSILqxGD6ubixIrtCfqapkdnngmsBQvlHZ9zc2FZ9O",
	"HLiRdQZ4dlNFdxaMwBjZX1yXsV7MMm0dq+4jD3vQUI3ezCgiLAvagh5pfMqKVEUj5G/6BZ6PkeuaNbE9",
	"7pr1vYeG9R9oyAteA6lFHPRTh+2Rn7qVZfPoS23h5+rjYFNVn5Uex22wZW8IP/I/npQTzvKNdpryOCzh",
	"DoVmYOrvk5xQHB0ECMF/ecT1KU1THeX/QT5Qq5/sH+wDtbtacO19QtWG2bmlIGkbldIGab8HpfkJnyUN",
	"H6h16fkhNe3LROS/kCf2cvryj183dPVqdDAKlf5LeYClhDS0oHf66o+8rMENVYO6wihLroolke9Xn8eN",
	"bwj6suF2fXcVh5Wekvdw+kmQYa8Kx/5Xld2gG33lLNvwLbCbkXhzw2yxWon70p6G2NQvcrqvjp8dlA3p",
	"ZFIuZGEZV7vHsWrGvcFChkzNM7bUyeq8y3K383UJ5ZSydsun6htOaMP/RBczfCWk+dmkpPzmSE83ngvr",
	"PpZ19n+Ycuo0YeyTDlvmFv9ZuuE7/q8ZoZ0PhQJeQj3f7I/LLv3lEX3hdF9er8r71IXuTjMeKuC9b0jM",
	"u0923/q84GXZMSCkcCK4TnVPQVZYN5urozF751OG5Xpl44CXijK5YufqeMwuCWMSvqqtYK5OxuwKVDqw",
	"p7KNl1t2E/Z3U30+JAUr1v6jB7b5XQYHEqz/KFH4wohHme7pk8I6nYlfodHxIPVaJP3IsM6RPSc27Ih8",
	"5Tv3krUHftaiejHWSt37tH072ZsboC/f/tLXiO2M71Opr47z2u49qbxDYhA/6tEuiGpCOJGGQznvtX18",
	"DJDOA6SZ/+jUuhAphhNbMLbOuyEA6ggpR7P3jY6QGfsBCsMlU+Du/JekDNDkjs84V++1qTgvpF9rbqeA",
	"oZvtjqsvAXlmGVmRwlzdSLGcVFNvWM6TW7ryp+8Nl6nzmpWebpFpa2xvVC5Cm8gf48i2e5z+wZ5sp8tl",
	"QGWGzYcD+rcj+U81VLj6yR+/ev3todLBKRqfQTsYcpMOO1bUg6it3q62d96WNppFHnV3O70jMVtXPS8x",
	"fcnI99d4f7ffvDIeiFDdX6tmkj9MsLptQwNUDkOaHST/HOerE564knZtzGgYcaMd+FRI494w8Gx16zjh",
	"uYgevjz8dwAAAP//eWZ0gdVgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
