// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// Inputs Input texts to generate from
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq model from models_dir/generators/
	Model string `json:"model"`
}

// GenerateResponse defines model for GenerateResponse.
type GenerateResponse struct {
	// Model Name of model used for generation
	Model string `json:"model"`

	// Texts Generated texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Generators Available Seq2Seq generation models from models_dir/generators/
	Generators []string `json:"generators"`

	// Gliner Available GLiNER models (zero-shot NER with custom labels)
	Gliner []string `json:"gliner,omitempty,omitzero"`

	// Ner Available NER models from models_dir/ner/
	Ner []string `json:"ner"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`
}

// NEREntity defines model for NEREntity.
type NEREntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// NERRequest defines model for NERRequest.
type NERRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of NER model from models_dir/ner/
	Model string `json:"model"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// NERResponse defines model for NERResponse.
type NERResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]NEREntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateQuestionsJSONRequestBody defines body for GenerateQuestions for application/json ContentType.
type GenerateQuestionsJSONRequestBody = GenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = NERRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ChunkTextWithBody request with any body
	ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateEmbeddingsWithBody request with any body
	GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListModels request
	ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateQuestionsWithBody request with any body
	GenerateQuestionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GenerateQuestions(ctx context.Context, body GenerateQuestionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecognizeEntitiesWithBody request with any body
	RecognizeEntitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecognizeEntities(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RerankPromptsWithBody request with any body
	RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetVersion request
	GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ChunkTextWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ChunkText(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewChunkTextRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateEmbeddings(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateEmbeddingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListModels(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListModelsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateQuestionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateQuestionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateQuestions(ctx context.Context, body GenerateQuestionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateQuestionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecognizeEntitiesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecognizeEntitiesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecognizeEntities(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecognizeEntitiesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPromptsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RerankPrompts(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRerankPromptsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewChunkTextRequest calls the generic ChunkText builder with application/json body
func NewChunkTextRequest(server string, body ChunkTextJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewChunkTextRequestWithBody(server, "application/json", bodyReader)
}

// NewChunkTextRequestWithBody generates requests for ChunkText with any type of body
func NewChunkTextRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/chunk")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGenerateEmbeddingsRequest calls the generic GenerateEmbeddings builder with application/json body
func NewGenerateEmbeddingsRequest(server string, body GenerateEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateEmbeddingsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateEmbeddingsRequestWithBody generates requests for GenerateEmbeddings with any type of body
func NewGenerateEmbeddingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/embed")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListModelsRequest generates requests for ListModels
func NewListModelsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/models")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGenerateQuestionsRequest calls the generic GenerateQuestions builder with application/json body
func NewGenerateQuestionsRequest(server string, body GenerateQuestionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGenerateQuestionsRequestWithBody(server, "application/json", bodyReader)
}

// NewGenerateQuestionsRequestWithBody generates requests for GenerateQuestions with any type of body
func NewGenerateQuestionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/question")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRecognizeEntitiesRequest calls the generic RecognizeEntities builder with application/json body
func NewRecognizeEntitiesRequest(server string, body RecognizeEntitiesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecognizeEntitiesRequestWithBody(server, "application/json", bodyReader)
}

// NewRecognizeEntitiesRequestWithBody generates requests for RecognizeEntities with any type of body
func NewRecognizeEntitiesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recognize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRerankPromptsRequest calls the generic RerankPrompts builder with application/json body
func NewRerankPromptsRequest(server string, body RerankPromptsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRerankPromptsRequestWithBody(server, "application/json", bodyReader)
}

// NewRerankPromptsRequestWithBody generates requests for RerankPrompts with any type of body
func NewRerankPromptsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rerank")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetVersionRequest generates requests for GetVersion
func NewGetVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ChunkTextWithBodyWithResponse request with any body
	ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error)

	// GenerateEmbeddingsWithBodyWithResponse request with any body
	GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error)

	// ListModelsWithResponse request
	ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error)

	// GenerateQuestionsWithBodyWithResponse request with any body
	GenerateQuestionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateQuestionsResponse, error)

	GenerateQuestionsWithResponse(ctx context.Context, body GenerateQuestionsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateQuestionsResponse, error)

	// RecognizeEntitiesWithBodyWithResponse request with any body
	RecognizeEntitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error)

	RecognizeEntitiesWithResponse(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error)

	// RerankPromptsWithBodyWithResponse request with any body
	RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error)

	// GetVersionWithResponse request
	GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error)
}

type ChunkTextResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ChunkResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ChunkTextResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ChunkTextResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateEmbeddingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmbedResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListModelsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModelsResponse
	JSON400      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r ListModelsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListModelsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateQuestionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GenerateResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r GenerateQuestionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateQuestionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RecognizeEntitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NERResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RecognizeEntitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecognizeEntitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RerankPromptsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RerankResponse
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
	JSON503      *Error
}

// Status returns HTTPResponse.Status
func (r RerankPromptsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RerankPromptsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r GetVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ChunkTextWithBodyWithResponse request with arbitrary body returning *ChunkTextResponse
func (c *ClientWithResponses) ChunkTextWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkTextWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

func (c *ClientWithResponses) ChunkTextWithResponse(ctx context.Context, body ChunkTextJSONRequestBody, reqEditors ...RequestEditorFn) (*ChunkTextResponse, error) {
	rsp, err := c.ChunkText(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseChunkTextResponse(rsp)
}

// GenerateEmbeddingsWithBodyWithResponse request with arbitrary body returning *GenerateEmbeddingsResponse
func (c *ClientWithResponses) GenerateEmbeddingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) GenerateEmbeddingsWithResponse(ctx context.Context, body GenerateEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateEmbeddingsResponse, error) {
	rsp, err := c.GenerateEmbeddings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateEmbeddingsResponse(rsp)
}

// ListModelsWithResponse request returning *ListModelsResponse
func (c *ClientWithResponses) ListModelsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListModelsResponse, error) {
	rsp, err := c.ListModels(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListModelsResponse(rsp)
}

// GenerateQuestionsWithBodyWithResponse request with arbitrary body returning *GenerateQuestionsResponse
func (c *ClientWithResponses) GenerateQuestionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GenerateQuestionsResponse, error) {
	rsp, err := c.GenerateQuestionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateQuestionsResponse(rsp)
}

func (c *ClientWithResponses) GenerateQuestionsWithResponse(ctx context.Context, body GenerateQuestionsJSONRequestBody, reqEditors ...RequestEditorFn) (*GenerateQuestionsResponse, error) {
	rsp, err := c.GenerateQuestions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateQuestionsResponse(rsp)
}

// RecognizeEntitiesWithBodyWithResponse request with arbitrary body returning *RecognizeEntitiesResponse
func (c *ClientWithResponses) RecognizeEntitiesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error) {
	rsp, err := c.RecognizeEntitiesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecognizeEntitiesResponse(rsp)
}

func (c *ClientWithResponses) RecognizeEntitiesWithResponse(ctx context.Context, body RecognizeEntitiesJSONRequestBody, reqEditors ...RequestEditorFn) (*RecognizeEntitiesResponse, error) {
	rsp, err := c.RecognizeEntities(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecognizeEntitiesResponse(rsp)
}

// RerankPromptsWithBodyWithResponse request with arbitrary body returning *RerankPromptsResponse
func (c *ClientWithResponses) RerankPromptsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPromptsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

func (c *ClientWithResponses) RerankPromptsWithResponse(ctx context.Context, body RerankPromptsJSONRequestBody, reqEditors ...RequestEditorFn) (*RerankPromptsResponse, error) {
	rsp, err := c.RerankPrompts(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRerankPromptsResponse(rsp)
}

// GetVersionWithResponse request returning *GetVersionResponse
func (c *ClientWithResponses) GetVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetVersionResponse, error) {
	rsp, err := c.GetVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetVersionResponse(rsp)
}

// ParseChunkTextResponse parses an HTTP response from a ChunkTextWithResponse call
func ParseChunkTextResponse(rsp *http.Response) (*ChunkTextResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ChunkTextResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ChunkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateEmbeddingsResponse parses an HTTP response from a GenerateEmbeddingsWithResponse call
func ParseGenerateEmbeddingsResponse(rsp *http.Response) (*GenerateEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmbedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case rsp.StatusCode == 200:
		// Content-type (application/octet-stream) unsupported

	}

	return response, nil
}

// ParseListModelsResponse parses an HTTP response from a ListModelsWithResponse call
func ParseListModelsResponse(rsp *http.Response) (*ListModelsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListModelsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModelsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGenerateQuestionsResponse parses an HTTP response from a GenerateQuestionsWithResponse call
func ParseGenerateQuestionsResponse(rsp *http.Response) (*GenerateQuestionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateQuestionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GenerateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseRecognizeEntitiesResponse parses an HTTP response from a RecognizeEntitiesWithResponse call
func ParseRecognizeEntitiesResponse(rsp *http.Response) (*RecognizeEntitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecognizeEntitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NERResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseRerankPromptsResponse parses an HTTP response from a RerankPromptsWithResponse call
func ParseRerankPromptsResponse(rsp *http.Response) (*RerankPromptsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RerankPromptsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RerankResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetVersionResponse parses an HTTP response from a GetVersionWithResponse call
func ParseGetVersionResponse(rsp *http.Response) (*GetVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9DW8bObLgXyE0B8TOa8mynWQTHRYHx+Nkvc9OvLazs++iwKa6SxLX3WSHZMvWDHK/",
	"/VBFsr/lj53JvAXeAAOMJZHFYrFYX6yq/DKIVZYrCdKaweSXgYmXkHH683BZyBv8IwETa5FboeRgMjhg",
	"Mf7A1JxZuLPsVtgly5UR+DsTcq50xvHv0SAa5FrloK0AgggyuYqXXHeBHi655rEFXYfElBYLIXnqF1qC",
	"Br84yMSwLbiL08KIFWwPooFd5zCYDIS0sAA9+BYNRNJd6AK+FiBjYLLIZqBpF8sAdWscsd2I7UVsNBr1",
	"wIwGd8OFGvpvCyHt/h4uZCzX9jfaGcEyvfvBsd0FLkv0YyUtSFvNNVYLuRh8+xYNNHwthIZkMPmMdPHA",
	"GqhH1fl8KUGo2T8htrg6scOhknOx6NklfV9oOng2V9qhJOSC4cpgrGFWsUvQmbDADs6OR1N5uRSGCcM4",
	"MyLLUzEXkOAm5mJBIPBg/nJ5eYbD2ZAlYj4Hbdhcq4x+mxdpyggt0A6BqbxdinjJhIzTIgHDcq1WIgHN",
	"DKQQE3JcJizm8RJxi+toj6ayw7EZv7uinRi35zkvUjuYvBxHLQKc8juRFVmNrdw03LUGW2iEDXc8y1Nw",
	"87vnm6kE0sY6g7m4AzytDUeOe6BZuExhYMSOhF2CZs9o4jMiIxEXmFU3IIczbpDIfnLElGbcg5A8A0dc",
	"+mx2Ykdas/ML/vRtZ1TfQolai9eigVqBTnl+RQs+RLcPJb38tBz35KayGdhbAOlJ+TABDeRcc6t0k4hT",
	"SSfboiFevHICEYp2VNKmsVkPorNXy/UCbP9WO3u9pMF1yeO2mYO/Ls0d9m7RLjWYpUqTxmLj0cuo70Ym",
	"JOrKObTLjx8+/MOfMNsaj8bD3dF4u74yAXNSHI85VbwmUhzyJFL6JcS5u+6IXvMqxaXo+F8a5oPJ4Ied",
	"SvXseL2zU5cym0Uenp1VXaINKpGSKrlgiYqLDKRldsktkwAJXcgZMJOnwjIhrWIm42kajsCMRqMHBShh",
	"9WUzBUyupAHSeAGzXwYoc+BqKexgMuepgWgQBMvnumbcxXNHzTVu6pVxIEa5RxKBQhvrMEfEv0UNUG88",
	"qN0mqDf9sAzESiY1YF9KkeQv+7e2eKztqX1GPy2BJJEGU6SW3XLDDOgVJE7E0MyK0DOlUuASV6iL24bd",
	"oTVfl1ZHKRKEhcw8iqsGFc9yhNUSuU2l3RCuPLYFT9M1itiEbWV87ZWR24vXcJAwMWdznqYzHt8wFceF",
	"1pBsP0Zqthis3J3DL6oRupftyqvVPB6ei6tC9+zv0/lJsHyCSoZsBkki5GKn1Cx4XiKGBv5La/PJzk6q",
	"Yp4ulbGT1+PX40FNXhRa9AlKJAlyZq6F0sKuG+Lr80BJeYfmVcoH0WChcJdNjN+6+SzMZ0qjWkeB5s4o",
	"VRyxd+aoomk8ZQngDpjJIUbzQpvRVL4jVCfs2uN0jUowfJi4GdfeJvPzPaYkPK55YdX1CDVCoJ3VAgwD",
	"6f5P5h0ih5ZGYaB+U/mKi5TPUmB+vf9wK0xlrLKZkM5+ImllijxX2rrZtEda8/lzTwrz/DnbSiBHqijJ",
	"ZoVIE2b5wmxPpnLIrhfqmg3ZWaGBvVdol4MmbbDF01u+NhUqETs8+8SUTNcRM6m6BWO3CQIeCsIgjXFe",
	"SCsyYFueTw0b4mJ/ntLZRR/PL6eDiM25seX8u5Tj9Pfq9OQf7B8nBz1z71Ie/ePkAKdenn3aOfz048HO",
	"4dmnbbfTH4k25vlztyMiPBuyg8KqYQIWYstm0KDqlj8ph0BcJITBh78f/3h8wBA6e3/2yf2mNGQpgcvR",
	"PDpUGk5P8HLHHy88Nei6z9ZEAAfR5oXbklqkgCizrTDoHycHflU35p3SMZSkdRs6cveo3NFnRz3cPtHC",
	"/bFQ08EXBHGp14FPjGNsJEHFlNaZtHVQE9xzCW9i88J9cL+FT+UKZxpQjL0/+xSR5KLlkMsPPZlKsESu",
	"1mxHK0LMk4/HMaTg7Olpw+T9XKHnLjriNohKxPyX7i8nAUrR3jW7WmLcez5XBuIiSJf79AGXdp6uhwt1",
	"lYoZn1+ZWHM0PK9UDhKl5qEDeOHhVQbJDUB+xVOxgqaNOe4YmH9Rt84IsYrhrGBzoaBCVSFZBpnSa8bn",
	"6B2m3FhkOLb1MU15xoeINrdilsL2aCpP3WSugXgAPezYqSTpATowFhV6EhwxNWdC8tiKlbDr0VR+MiQM",
	"kpqjRqJwOniZTQds6yXLhCwsmG08590lfrfLlqrQ9MUYP0tYgfbLRgz4ApF3whcR/WkJkhkg+8zNUJqp",
	"TFgLSRRogNvwaBOAdM1Q4qGNUuQkN+uroM5NYcHjNZvBkq+E0tujJncNXmZ9WidVi6eyQqoWixYn+KMn",
	"X1BJ0urSXgW/tmmIP8IvLEHUhHLpJPMUJXAymsqDJBFei5W/3gq8osC+FlBAwoocqYx40RdXRvwMo6m8",
	"cNQfk3YsZCpQSSWVbGzR7kWvL8rvrhztr9yZPXWb/qQD83e43oisSC2XoAqTrgPjEPsSwmiVakCzJ4lI",
	"BaaAN0RDDNIGU8ypfmFqjHJy/omhfETEth9DDPZRpmsG8zkK0xWg4pesuuYIXSo5/Bm0ahFufxPh3Bav",
	"stnjiOYpsiUkO3277V15wtdvytGyn0Y8z7XyZNpIInfjApEeRZXSk5KMJythEEO36NDbwx7vqSwMX6A6",
	"yklPKemPBbnR0GVGg9lClivNtUBi38UAidvIiqcFMu1PSt8g+yu5MCIB1mFA76JLGC40F9KFiqxWaZud",
	"x29ebTqY6po8lZ3rUSyC4vhkg0yoMW91av7a4m/zIk0jJuG2gounhuz2crzPLpzhzT7JyrIhLXsOVq+H",
	"ByTpl8AT0JvP0i32AJ9vwn9ajMf7wMYt2u6ONweurozV3MIi+B6l+DprxYCLDK0BkvuDaJDyn9eDaDBT",
	"hUwgqbk3lRRvns0Z6GHT5PcLrymEpEUCZsROeW5qcS06N7sEoTuzKuUqFYpkx5YZz+kW4rF5ElbruCCa",
	"qosJsueO57Vv/uz1ZTiASVNXsi38o6b2oobO2+7Ac0cynjCkWAuKkiyBjMsk8tO9NSCSFMiWJhYMgb4l",
	"+uJhL1N3EtNBfetuNyRfgnVRqectbljOtcVrkWuosKXxTcUdMViBbMtUvxW2lQsp61qBcCXJQ3rQsEzc",
	"4S4d5VCU0Oa9QBDuVhmeActVRxD8MpgtYEjRnSHI4Wp39HIwKfkuXip5sx5MHAP2hbPcKleJ6Inqv+UG",
	"WCI0xBYFI0oiLmQVMTDFLPwqkB2Dp8jJdREmRlY1YSNzrTLnEPxSLfptx7nkoM0OGttHwUEvg3eVW9KY",
	"VoZtcVYzkrF5kgbNq1nn9Kln2lT+WHOF/9/OyLqN7YRxaPmtBGcrkYPeHiEL47UyYCPyg8hPtUMhW9FW",
	"UjVB2LWNu846fbaeZ8XuWZ0IY0uLpJIGfnyDs3tN78slGOixXEWWQSK4hXTtGDwcsnvCiRhfKUEHRr7/",
	"0AtXlnILMi7ljsfILFWRoqq08ZLZpTJA16I8oho3sC0YLUZokHcYfDpAjB9v0bCthjTB5drm4eeeaxQN",
	"4lTkw5Ww9KAwzBHr/b2nOW2eHldWZKAK+5A/FXQyRSGsYrdcWFJ5PChRCgkrxNpC5N+AcFdeX+N4nHyv",
	"H7Q/Ns7J3c3c/53Po5jHMmI1K/o8qEtn0NDLBQovP7am01+w99zCLV+zS/dbm8X3x71MbfavYg0JSCt4",
	"ap7s1u5XbkwNSjvaGMKEG0KL6AifcW17n4Ldz04fUDCuSK3IVMLTKqLItihkqzQTGV/QY62S8HFOke/7",
	"9nMJd7aOwLfo/vHHCP7T+Uljzpdv0YBk58aXCSHzomd3x/h1uUOr3IZG7KIKzGkAzzuG5PeFkIsUXITa",
	"HeKEXU8HS0hTxW6VTpPp4BoHNoPZbqiZULiFBjve8zO+NKfUaW7YVkXxbQTwy5QOcTpAbkboDpT7C7/z",
	"8L9FrDGUjgbZwI2vfZzgQP/XdJBwyyf0604uF/8br/+rF9FoNJoOvn1DTJuyo7b1Adrg8VJI8uU0aktk",
	"uYoVWi/1HVqyrRmPb265TlhNQvdcm/ufDjy1N0J7tATbuEztErQOq3ERzPaj3y8al6CFx5fN7xgf0DTy",
	"gf6gP7werD30ttRLQy71yf4uXXQhY26bTpXVBXReQP1ARlcO79RcWI8QUerOshTkwi57noZaUis8jbjb",
	"2ye7/K3vfY0rhZMZTD5/Ho/Gu3v70XA8Gr94+Soaj8Z/ev3mS4Tf7+2/oO9fvvoTfv/6zZfas1iXOp0n",
	"svpCGxmmEpUrshkN21IS6GHYUcrRusEv5R8PPdV2Ne8jX8GceUJRBBTtJZJPZZANB1ejTO/pae0e8lv0",
	"DF83caXRLANj+AIeRMEB6Vv1PUhAz+h+ZWE2aQvkYLIuFx4O3bOmSLzUXBo0AnHce9AZlxP2F5STEVuq",
	"WzIx16r4P0+zph6QABfwde8Cvm64/B5b1b7985TLoX3pDvjRB+tJdD95q1vZyri5fx9Zkyc94jimTy7h",
	"aXRhBSQSf1xbPNxD+sOgp1K7fJGT53nqvpsBz/ov4oNn1Py8gXoO6T7iBfOmh/nwF0avupqhhmafzo87",
	"yUybn4KrSWxro4JvPmT3DxN/f/vx/Hb8n+8X6jGJFJuszj5DbsOmg4JtSCi29TEHeXBc8+S8nbbdoUpp",
	"6TykhEvylydZRbMqIF8eTB7BX6PeGRUBXERq8y0JPn6PTikjhnHb9fcPv2Vy3NRlI0wH200BFXIUXIhk",
	"mKEasV7I01VIhVwUPB3uPk1ElSbGfVhDO8zxOEOl30vtfDcUr4df7dPQroTjfXgHAVtJpE0b2CBsP3ek",
	"bZp9XQxJDQklhzVR9zT0UyFB34f6+xPx4ei8ZJOfQauhWSrL8FuKO8eFsSpjKZ9Balrc4uCXSPuPxCeW",
	"m5unIfsApjU021SVoNsMgVxL4QlJEb9EGCtS+tZ90cD8iaELHy27D1ndCqJ12TWAGa72htn+U1DoyxdC",
	"dOqo1S+co2yDl/vEzoej8yNp/QN6J3f7vuRmNZ8bCJnMQDD6krRrLwl9DwnEYD3GnYOH49nW2dF5xD6e",
	"v4/YycfDiJ0eXxw2NdPZ0XlvKCVWGjZkLrs8SRpBOZFomXXTIt+8iR5hbFP076mkmsFCyAaHjJ+WAe7h",
	"+Kzuihh/VUvJLjJR96juy2oMZxD2QUnhg0C9DTyz0Vh2AqOHGE6eeKTdKIqw3FkkEttqiiQl03WZW1AY",
	"vFK8IbUiNJhZzKXP9FozLtclTdY51KFHUwmSz1CJsa6sU0VwSDVY7YL6o6n0cWyfT+6fpGncM1M+EPmN",
	"0Furoae/5p3PQRuyVMkskWtniyRFjHRO0IH+LU3+kjoPysqOqHysJX0Z3J1wcERyAabH7ak4kd26t17r",
	"86jQTnRJWMcyHjFBLzuHBfGRVKNfIRcftqmJezdZWWE393nujsec49D22nHZflfhPjuzEsL/uuu+wV36",
	"0CcaN7nnYfN9ZHMPRBvv/QNYtTRjhz+rx6hOqKGlMnvfgVSW9zHrmcbpMgENSS0zPLCwgzxiVFyRCsrP",
	"MUw75ggeRGB0IRdTyWXCHEBRzzWfC0gTs2Mhy9HLN2wGc1QsMU/T8okAZJIrIW1HRhxL60QCJYIq1g6Z",
	"OrfqR8qp8V+xeSETjmvzlPLXnyRFvhag132FUlzHS0a/0s41pLDiQU+2w0BtNBnP81TEZK+aR/Ocw6U6",
	"w/tY77cJIJSsuNFk6OGk8wYpoHbvHeKRe5P2WcDGSYOGIHhqzG4DvTyCfWRqv530F1H0es8dF/meKoz2",
	"80iv8mg5y63yifv95I21Fn8HbYSSmxmBMqLpdbHn/d5lS4sMjOVZ3mDlvfHei+F4d7j78nJ3PNkfT8bj",
	"/9u3rYWwV7HKsr7qh/cCSYO/sSU3ywZ8Pot39/Zf9IJUVyu3rR6Qimmfgx3G1KEu1O5o7+Vo3Ad2I8zw",
	"Yt0HcLU7GveBax1TNbVGj6hO/Ma2+k6y/WwZAhfV4+Uflah/VKJu5pcNKbvdRBA3rln1SaKvzNxwiXem",
	"wy8prCD9tanEJwSETmntXqF+DbQLAtJbiPc4RBr5FnhbOikXgWAr0DNkmTVzdIhKUZ7ArFhQyJ+m33JX",
	"5xqeVypp4gd0RNPjdtlAlVKBJE83oqsKi9a3u/6MiD1iz8I0VxQbq1Rp8bPLIjUqhYg9+6dR0pfMWl3E",
	"tkBD8a8XHz9E7FmqFvPMul9dJS3M5yImM/EG1n+mNFaWc6FNxJ5JpfJQfJuCtKMayWro/9N5gw72IBrg",
	"tCbZaoMfJN2GbI9uVVgcgzFXN7C+6pNLBz9dMDcEN8aOf6xlPNzA2li0Zc1aWn7ndgixBstSpW6KfMTe",
	"8TQ1ZRnJwU8XVweHh0cXF1f/efRfV8c/MpAroZUkS3nFtaBQmSizxJo1xmtV6KFDZngD66HotS+CLd0j",
	"Y/frLwBhXMifemb2RzzjPyvJb80oVtkzpjQedahtezMej90xngp5/LEZZmpPHkSDTMgT93o92e0zJ4lS",
	"VxX9+4nvCVqdwa89gIujw/Ojy9o5/AuH4BapnUWvvQwGlbwrh+5u7mOoynO7pLHuMrlr5TPE16yW8vSk",
	"vfehTasMHUY9KBcGroxJH8xcOJIuyn9xsnN5ckFrX+yj7JCuBsuUib4ThvNpxMFPF1RWVWbzxzytWKkn",
	"v+FBSf7IQqXunXdlJVfI1qavWFdYSH2epB/LcCzlJu4cn7ns+1TIG5aoW0ruNZTcCVlu1xHOofG+QslD",
	"QLMIcstyLVbcAkM4Ys5mqYpvrvyXVyJ3Fci6gO1R0xf2f/rbFSdy1Pxm983eaDzaGz3xHSoQI+d2+Vhi",
	"4FiWa5iLOwilCClMdnYoK9ns41+fzk86RKE16kQZsXe1yYUBxmdGpYUFP9YLp51PBrTZSbjlO9tuklsF",
	"p8yK+AbsjsMnzMjWQ/99kdMB7bTpWYeJ4qoz4Wl07Jzjg7foLc5o1FJUrME0lwv0pXf3/oSex2i88zpi",
	"u+Pa33/aG+2+ok+7exHD09999dp9fhWx3VdvRnsvX/jP273F5YF5Q9LplSt6b2K+3+3c4BM68dyFTMRK",
	"JAVPy6vA8Kq5UAea1AFmvVRoTNpBZGgD7G4qTymxM+JnuJqtLTQR2x2/eP3yT6/GG+tVcB5ybQDki2Rc",
	"rRlzABuPMCW8ErnxA76GkPbVi4Cwe8RORAaycjA9snvjF6834Unz2K1I7HJnCWKxJPxycUcPkC45rix2",
	"04DbatbRO+D3UbQrTfErMkNdMwrLY7IYUMSh5iVJO4hclgTVuZvJzs5C2GUxQ3njDfJktuNz0bulKcGN",
	"cGVTPpk8FTfgRX9V70etEHTZj8O3ZTk9qUq9pvKHH9hPS05RSA+4XnPuXyJM0ConNeiuVLjEoGYCHZwd",
	"U6Lq8+dVOcH78mH5+fMJo6gOFW1VSYxbhyfHZ9udp3kHiCaEMgOEcAEZl1bEVQIC4VPvOxKarQyJYUPL",
	"BAevrD1AWFWkTcPQxx294qfwpOsu4TH5wDNImH8sPIdYLaRzc7c+HJ1vI7gj/0zhHmJMxJRecCl+dnc3",
	"Ilq6a+yaDMGddaDfFegNIIjDlBsj5j60SZQKL/MrKKs/yGRhecqlhITKJoKooFJGboEK9VLgqAAsC+zm",
	"eGwk1E6iYrNT6tqSH4CCwp8M9PFEzCXThUTPXSY8VRKov09VrsMlc3zO4rQwFjQxwwlxUHU+LU5CwQd3",
	"FjSZbmfHvtIPZCyAKN9ls+sdnguXqXFdmd2NICPNLFml6ukRDvj84D3LRQ6pkG6VOiuE5wOSxxleBUgC",
	"S3wteCrsGqccgrSap+Tm+ZNBB18uGI+1MoYlArXbrLCQMKkSt9AZqqR4Pcw1hOGN20UZUr7OKQW+AsPQ",
	"1sQRmpee47Y/snfA8aM/wR9Y371zPOZyfpDH6lelUTEUuqdsrBNykA7OjgnM484lXDsXR2WuPQbh8VZI",
	"NMfLEraIvOGwk9NKQHgb3QsKB9ClZ5XbJYD4M6uVc/6T+AIPf+hUQiViTM5j8JDoMa2OFyWblTlrhm1d",
	"b8xau97GO4CmmQPmE8MOS6IgwE8GTCtV20cPtq7/pSx5nw9/7WmB9/WQG2r8wBxhHLdGjBhx6MiowWoB",
	"K55GbCUMWhhGZCLlmvjZUb0hbtuM864SquVl6vT72Gb/UeewGgz2o+ezNQI72FirtrHgzME6dN3VEMbe",
	"0DUUYJeXJ6HOmXrZeLHqJT/h3vBb29Vh4eFmzkVa3qVSVTx2D/WL1bORWhGcg/i3AsXTz6VyPGi2XkCu",
	"+eqGVJXWYl6Rusa/OL3xAkkizz90sS3/4rjkMknRwRCQJuVjo5Lb9EyYihj8U0ewWtKUnaP9ZNg5uP5K",
	"HROm0ikpLDgFIK2wrl1W1Y9vUHsmGKx2eZov+S61c3Oe5mAy2B+NR/uDaFD6Te7kydtUpi/8kqcCzXzc",
	"aU+rLZ/KYYISaFoFrfTFYBKdeqZ1HEAMXxU5dnndVeV0GuBR+y9b9Qtyvedw8KdQ6/fnMj0Sv37HjTOL",
	"EnAxOWGsiAMaxFen5XXqWkBlxXAQMvWLPWSn98n62sN486Y9+cYwfzPx07mznMg1pRtZb86Asnkv9AIZ",
	"0TSgaGCZOzpTdhl6NSJZbO0xMByV73aDn66vr/9pUNH9MpWsUY60oWMbCdDIDXbLOBErGcOvaGsOgD+k",
	"KPzUaMmHQ16Ox+WPzd6E7tfyx7IboAM8nUr8b4A/f5vKb7QLuoelu3echGZhl+4Rw7u2b1WyDm4GuMBk",
	"7T18h+K+ZbPVRzUvC6kW35pPKOhk0xdOedOt3BuPf+u1/RMrLd73CExsmTBTUHhwXqQpBQhe/IaYuHKQ",
	"HgyO5YqnIglRBVz35e+zrjeJvS8HfmA0MEWWcb0OrNEj/wwsMuq4i8OdPbZZioZyBeOLg2o2tA9I1OsU",
	"nUxNWya9Ce1WS2NcmFrZm/fQyF58ZppmojeEXIT2zkYu7wUdApkYJvyzazffvuY/Bn8IYdRMwK5Ib3U5",
	"ulcW1qvjqxpuX9yLXpbbhZtR80KsYhTcq1pr1LAJDu2QatUzb1iFCFsnnXx7wg5iCnHWKwu9NVLtvw2H",
	"rOTmVKSpj3usBK9MW0+ihgnsmiTUak+JYJ7IkHzXStS+GvnN1amPKkh1tvL3KUftKQTZ/pW6sNa+iR4p",
	"4nqDJk49A5PCSRt0/b2NQ8cxTynU5ZoPrBCEhqSQCZeWciLDhWj7Yvh1+QxSFiOVqTeU34pc4xnKdYbx",
	"PfNqgk/FFuzQWA08uy69OwNaoI/s4hnB14tYpoxl5SPndgcaitHrCXmEIUvOy5FaO2ESFTWXv24XOD5G",
	"rqvX7XS4a9K1Hmrav6cDgrcaSCzioM8ttkd+aqerTQdfKg0/lae9VexdVroft94eCX34kf3x4D3hLF8q",
	"qyiOw2Ju8dL0TP11N8cXcPkLhOC/3GP6BNVUefnfyQZqFPD/zjZQs4wY1950qZowW08fdNuG4bZB0i36",
	"rbdRndHwngSajh1S0b4sOv33scRejF98/3V9GxWFBkYhk38rCzDckJoUdEZf1VVvAbYvxdQWWhoyVQxd",
	"+W6FXFTr417GRCP24eg8asSly1K00jELppMzebpRkX4zC8f+rQx3UN6AtIYt+QrY9VC8vmammM/FXVCw",
	"3ll1ixxsKj5kW6ElEOmYs7QwVL1xL1Z1R9irTB+6ecSWWmGeoyy3a5f9EKaEDDEXu//hB6TpIwBL0A7k",
	"cdhls44FTYlGxYmH/r6synKLNIq1e9apVRDScpcvI/bu5ODDEP94e3B+6c7/5PRv71moH+xyQ8vgrtna",
	"aE77FnT1npxxaGjX0QMnwtjTUOT23QRxqyh2kyQwIY763yUH3/J/T2/0pM/tcdIocMnDXmjJUCF812LW",
	"rR5mBBuPtrveXhX3eoy/12b61rokhUDGKgE9opbULAH6NBRSWP+Vi+BVgygRgxy2w5Yz/IjL88MPrAzs",
	"B+fxb2FG81W1h3q0QS7NLehh6H1C+YMlIL3eBMVUxRmh2KqMnJlu9O2d0r1bqTbqNnW/OdsoTx6arwVP",
	"hl8XTXvWeIN70d7vxLWUjJepby35FtZKxrDpa5Q7JIoMO7KWs79SkzQh2SFPRJrymB54dWJGDdN9o4Ua",
	"zuV7GajtviG/s43a6auxKVT3h4n472Ai4ur733/1SnqU+ryotZTd6jN4tjcZsKXkchpDu/wK10m3X2Wc",
	"hyGGggFJVR269WAChlcaVR6G1zZkf1UmVWnRuqSPy3XuRPEFZUDohB2qDycnjUpgn/9ydnROT3KEiO/B",
	"WPZVrGpVpwP/hPvx/D29qdfxrSa4QlbncVelrOXkk4+HOPmkTC8pJ36AW/ZfSt+4qe80lzGU006PL2je",
	"qTAxpKlrll1S8Vfq09JYLSNLX7u2/ZZr7Stek7bc7lOUfyko6/4dj4G9PTq/9C9s1RnhpKYdHOLBcV8Z",
	"+EpwF751n69ZzjXPwIJ++FmpHhiqlzSXSoqqPb2OuqcguX2QnZrk+5VOyfhHoYb2+yidWun976xv6mXT",
	"fTGJcNH9C/Yf6uZ/grrBG/4v65nyzrR0RdA26LLfp2qGvhQ335hjUb7BV5XMVjHuS5xr6qXduCUomUOX",
	"o3EeSsJFWsrhWtF4Vhg7mcrdUZlt6NcLleEdc31vxM4JY4p7lHXjU7k/YhfuHz1q7yn0sOSGXfv9XZe9",
	"sxMwYuE6/pp6U2ILKRjXkd+313YoUyK2k8VI/6qkPVULEf9av60VbenRNsFzdLOuyh9I57gUqmbiTU7/",
	"ak2vwmpm3zxFX3SaC5RKgxjEjbq3zL2c4E+kFtyfdur6Tz2kEw9p4v7FhUUhEmAuXanKgUAAVPIfRrN3",
	"tZL/CfsAheYpk2C9JtNAk1vxe+cJBs7zirridlLn7cyjqGyD75hlaEQCU3mditlOORWVdHxDOd3072+G",
	"NKaKlR7ugdBWoQj6zPcB+D7qs9nE4nfWoK02Bj3i1G/eH9AfKvR/ggqtGu//CkWKICqtt670ndOltW4A",
	"9z49tJoDRGxRNjWIwj83JzJwQbVud4JRTyzG/r3sFvDdLla7L0QPlf2QeouA/57gcMvTtoF2TcxoGHGj",
	"6emTXcvh9DxbZoDu8FwMvn359v8DAAD//4dFPKrlewAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
