//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Backend.
const (
	BackendGo   Backend = "go"
	BackendOnnx Backend = "onnx"
	BackendXla  Backend = "xla"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for ModelType.
const (
	ModelTypeChunker    ModelType = "chunker"
	ModelTypeEmbedder   ModelType = "embedder"
	ModelTypeGenerator  ModelType = "generator"
	ModelTypeRecognizer ModelType = "recognizer"
	ModelTypeReranker   ModelType = "reranker"
	ModelTypeRewriter   ModelType = "rewriter"
)

// Defines values for QuantizationType.
const (
	QuantizationTypeBf16   QuantizationType = "bf16"
	QuantizationTypeF16    QuantizationType = "f16"
	QuantizationTypeF32    QuantizationType = "f32"
	QuantizationTypeI4     QuantizationType = "i4"
	QuantizationTypeI4Cuda QuantizationType = "i4-cuda"
	QuantizationTypeI8     QuantizationType = "i8"
	QuantizationTypeI8St   QuantizationType = "i8-st"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers   RecognizerCapability = "answers"
	RecognizerCapabilityLabels    RecognizerCapability = "labels"
	RecognizerCapabilityRelations RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot  RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleTool      Role = "tool"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// Defines values for ToolType.
const (
	ToolTypeFunction ToolType = "function"
)

// Defines values for ToolCallType.
const (
	ToolCallTypeFunction ToolCallType = "function"
)

// Defines values for ToolCallDeltaType.
const (
	ToolCallDeltaTypeFunction ToolCallDeltaType = "function"
)

// Defines values for ToolChoice0.
const (
	ToolChoice0Auto     ToolChoice0 = "auto"
	ToolChoice0None     ToolChoice0 = "none"
	ToolChoice0Required ToolChoice0 = "required"
)

// Defines values for ToolChoice1Type.
const (
	ToolChoice1TypeFunction ToolChoice1Type = "function"
)

// Backend Inference backend
type Backend string

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Supports two formats:
	// - Simple string: "Hello, how are you?"
	// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
	Content ChatMessageContent `json:"content,omitempty,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCallId ID of the tool call this message is responding to (only for role=tool)
	ToolCallId string `json:"tool_call_id,omitempty,omitzero"`

	// ToolCalls Tool calls made by the assistant (only for role=assistant)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// ChatMessageContent Message content. Supports two formats:
// - Simple string: "Hello, how are you?"
// - Array of content parts (OpenAI multimodal format): [{"type": "text", "text": "Hello"}]
type ChatMessageContent struct {
	union json.RawMessage
}

// ChatMessageContent0 Simple text content
type ChatMessageContent0 = string

// ChatMessageContent1 Array of content parts (OpenAI multimodal format)
type ChatMessageContent1 = []ContentPart

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (eager loading).
	// Defaults to "5m" (lazy loading) like Ollama. Set to "0" to explicitly enable eager loading
	// where all models are loaded at startup and never unloaded.
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive>0 (default "5m"): lazy loading (load on demand, unload after idle)
	// - If keep_alive="0": eager loading (load at startup, never unload)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// PoolSize Number of concurrent inference pipelines per model. Each pipeline loads
	// a copy of the model, so higher values use more memory but allow more
	// concurrent requests. Set to 0 to use the default (min(NumCPU, 4)).
	PoolSize int `json:"pool_size,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "BAAI/bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// FunctionDefinition Definition of a function that can be called by the model
type FunctionDefinition struct {
	// Description A description of what the function does
	Description string `json:"description,omitempty,omitzero"`

	// Name The name of the function to call
	Name string `json:"name"`

	// Parameters JSON Schema object describing the function parameters
	Parameters map[string]interface{} `json:"parameters,omitempty,omitzero"`

	// Strict Whether to enforce strict parameter validation
	Strict bool `json:"strict,omitempty,omitzero"`
}

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`

	// ToolCalls Tool call deltas for streaming tool calls
	ToolCalls []ToolCallDelta `json:"tool_calls,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content (null when tool_calls is present)
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`

	// ToolCalls Tool calls made by the model (only present when finish_reason is tool_calls)
	ToolCalls []ToolCall `json:"tool_calls,omitempty,omitzero"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// ToolChoice Controls how the model uses tools. Options:
	// - "auto": Model decides whether to call a tool (default)
	// - "none": Model will not call any tools
	// - "required": Model must call at least one tool
	// - object: Force a specific function to be called
	ToolChoice ToolChoice `json:"tool_choice,omitempty,omitzero"`

	// Tools List of tools (functions) the model can call.
	// Only supported by models with tool_call_format configured.
	Tools []Tool `json:"tools,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelType Type of ML model
type ModelType string

// ModelTypeInfo defines model for ModelTypeInfo.
type ModelTypeInfo struct {
	// Description Description of this model type
	Description string `json:"description"`

	// Icon Icon name from lucide-react
	Icon string `json:"icon"`

	// Name Human-readable name
	Name string `json:"name"`

	// Type Type of ML model
	Type ModelType `json:"type"`
}

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`
}

// QuantizationOption defines model for QuantizationOption.
type QuantizationOption struct {
	// Description Description of the quantization option
	Description string `json:"description"`

	// GeneratorOnly Whether this option is only available for generator models
	GeneratorOnly bool `json:"generator_only,omitempty,omitzero"`

	// Name Human-readable name
	Name string `json:"name"`

	// Recommended Whether this is a recommended option
	Recommended bool `json:"recommended,omitempty,omitzero"`

	// Type Model quantization/precision type
	Type QuantizationType `json:"type"`
}

// QuantizationType Model quantization/precision type
type QuantizationType string

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// RelationLabels Relation types to extract (for models with 'relations' capability).
	// Only used when the model supports relation extraction (GLiNER multitask, REBEL).
	// If not provided, the model extracts all relations it can detect.
	RelationLabels []string `json:"relation_labels,omitempty,omitzero"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`

	// Relations Array of relation arrays (one per input text).
	// Only present when using a model with 'relations' capability (GLiNER multitask, REBEL).
	Relations [][]Relation `json:"relations,omitempty,omitzero"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// RegistryModel defines model for RegistryModel.
type RegistryModel struct {
	// Architecture Model architecture
	Architecture string `json:"architecture,omitempty,omitzero"`

	// Backends Supported inference backends
	Backends []Backend `json:"backends,omitempty,omitzero"`

	// Capabilities Capabilities for recognizer models
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`

	// Description Model description
	Description string `json:"description"`

	// Id Unique model identifier
	Id string `json:"id"`

	// InRegistry Whether the model is in Termite's official registry
	InRegistry bool `json:"in_registry"`

	// Name Human-readable model name
	Name string `json:"name"`

	// Size Model size
	Size string `json:"size,omitempty,omitzero"`

	// Source Model source (e.g., HuggingFace path)
	Source string `json:"source"`

	// SourceUrl URL to the model source
	SourceUrl string `json:"source_url"`

	// Type Type of ML model
	Type ModelType `json:"type"`

	// Variants Available quantization variants
	Variants []QuantizationType `json:"variants"`
}

// RegistryResponse defines model for RegistryResponse.
type RegistryResponse struct {
	// Models All supported models
	Models []RegistryModel `json:"models"`

	// QuantizationOptions Available quantization options
	QuantizationOptions []QuantizationOption `json:"quantization_options"`

	// Types Model type metadata
	Types []ModelTypeInfo `json:"types"`
}

// Relation defines model for Relation.
type Relation struct {
	Head RecognizeEntity `json:"head"`

	// Label The relationship type
	Label string `json:"label"`

	// Score Confidence score for the relation (0.0 to 1.0)
	Score float32         `json:"score"`
	Tail  RecognizeEntity `json:"tail"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// Tool A tool (function) that the model can call
type Tool struct {
	// Function Definition of a function that can be called by the model
	Function FunctionDefinition `json:"function"`

	// Type The type of tool (currently only "function" is supported)
	Type ToolType `json:"type"`
}

// ToolType The type of tool (currently only "function" is supported)
type ToolType string

// ToolCall A tool call made by the model
type ToolCall struct {
	// Function The function called by the model
	Function ToolCallFunction `json:"function"`

	// Id Unique identifier for this tool call
	Id string `json:"id"`

	// Type The type of tool call (currently only "function")
	Type ToolCallType `json:"type"`
}

// ToolCallType The type of tool call (currently only "function")
type ToolCallType string

// ToolCallDelta Incremental tool call data for streaming
type ToolCallDelta struct {
	// Function Incremental function call data for streaming
	Function ToolCallFunctionDelta `json:"function,omitempty,omitzero"`

	// Id Unique identifier (only in first delta for this index)
	Id string `json:"id,omitempty,omitzero"`

	// Index Index of the tool call in the array
	Index int `json:"index,omitempty,omitzero"`

	// Type The type of tool call (only in first delta)
	Type ToolCallDeltaType `json:"type,omitempty,omitzero"`
}

// ToolCallDeltaType The type of tool call (only in first delta)
type ToolCallDeltaType string

// ToolCallFunction The function called by the model
type ToolCallFunction struct {
	// Arguments JSON string of the arguments to the function
	Arguments string `json:"arguments"`

	// Name The name of the function called
	Name string `json:"name"`
}

// ToolCallFunctionDelta Incremental function call data for streaming
type ToolCallFunctionDelta struct {
	// Arguments Incremental arguments JSON string
	Arguments string `json:"arguments,omitempty,omitzero"`

	// Name Function name (only in first delta)
	Name string `json:"name,omitempty,omitzero"`
}

// ToolChoice Controls how the model uses tools. Options:
// - "auto": Model decides whether to call a tool (default)
// - "none": Model will not call any tools
// - "required": Model must call at least one tool
// - object: Force a specific function to be called
type ToolChoice struct {
	union json.RawMessage
}

// ToolChoice0 defines model for ToolChoice.0.
type ToolChoice0 string

// ToolChoice1 Force a specific function to be called
type ToolChoice1 struct {
	Function struct {
		// Name The name of the function to call
		Name string `json:"name"`
	} `json:"function"`
	Type ToolChoice1Type `json:"type"`
}

// ToolChoice1Type defines model for ToolChoice.1.Type.
type ToolChoice1Type string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// AsChatMessageContent0 returns the union data inside the ChatMessageContent as a ChatMessageContent0
func (t ChatMessageContent) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent0
func (t *ChatMessageContent) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent0
func (t *ChatMessageContent) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessageContent as a ChatMessageContent1
func (t ChatMessageContent) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessageContent as the provided ChatMessageContent1
func (t *ChatMessageContent) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessageContent, using the provided ChatMessageContent1
func (t *ChatMessageContent) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessageContent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessageContent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsToolChoice0 returns the union data inside the ToolChoice as a ToolChoice0
func (t ToolChoice) AsToolChoice0() (ToolChoice0, error) {
	var body ToolChoice0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice0 overwrites any union data inside the ToolChoice as the provided ToolChoice0
func (t *ToolChoice) FromToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice0 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice0
func (t *ToolChoice) MergeToolChoice0(v ToolChoice0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolChoice1 returns the union data inside the ToolChoice as a ToolChoice1
func (t ToolChoice) AsToolChoice1() (ToolChoice1, error) {
	var body ToolChoice1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolChoice1 overwrites any union data inside the ToolChoice as the provided ToolChoice1
func (t *ToolChoice) FromToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolChoice1 performs a merge with any union data inside the ToolChoice, using the provided ToolChoice1
func (t *ToolChoice) MergeToolChoice1(v ToolChoice1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ToolChoice) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ToolChoice) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Generate text using LLM (OpenAI-compatible)
	// (POST /generate)
	GenerateContent(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Get the full model registry
	// (GET /registry)
	GetRegistry(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Rewrite text using Seq2Seq models
	// (POST /rewrite)
	RewriteText(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateContent operation middleware
func (siw *ServerInterfaceWrapper) GenerateContent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRegistry operation middleware
func (siw *ServerInterfaceWrapper) GetRegistry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRegistry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewriteText operation middleware
func (siw *ServerInterfaceWrapper) RewriteText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewriteText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/generate", wrapper.GenerateContent)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("GET "+options.BaseURL+"/registry", wrapper.GetRegistry)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("POST "+options.BaseURL+"/rewrite", wrapper.RewriteText)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9DXPctpIo+lfwmFdlKcv5kGQ7jl6lthRZdrQr2TqSfJJ9HpeEITEziDgADYCSJrm6",
	"v/0WGh8ESXA0cuLsqbupOnViDYEG0Gg0uhv98XuS8WXJGWFKJvu/JzJbkCWGf/6IsxvCcv3PnMhM0FJR",
	"zpL95JjNiCAsI2hqm6QJYdUy2f+YcMbukzS5L3CSJnOefEoTtSpJsp9IJSibJw9pcrjA6pRIiedEAy8F",
	"L4lQlMCoGWeKMKX/+f8KMkv2k29G9RRHdn6jAMah7fGQJoIX5LGe57rNQ5oozourDBfFFY2t8TXiM6QW",
	"BOl2SLdDakElWppBEZVIEFlyllM2R4qjLc6KFZpxgfQsftDdtpPI6v24sjvqpRtLoiXOCZquYApYSioV",
	"Zqo9iP+gR6KKLOVjq9cjHOKigJmYqWEh8Cp50OgjnysqSK43ElBZ7x6f/koy1dq9w3qvmuuw35HdzCG6",
	"qMqSCyWRuuN6+kus5P6EDdAFXZYFQQY9+2iS/ESKgqdowe8QFgStePXvk0S3PNDT1JtigaISa4Bb70vC",
	"Do7RsioUXfIcFxb+9j76+PsE5j9JNGRF7tUkSf2//GiT5OHThCVpwhl5P0v2P7aXYyepu7nRIzvb7vXk",
	"CW+6hxbtZ1io7jZ+gi2q2E13Vw5Qpj8AYeul3FG1QCWXVH9HlJlpUM6GSdo6lYTlV9kCiy7QwwUWOFNE",
	"hJAQF3ROGS7sQAsiiB2csFyiLXKfFZWktyQ4IpQpMidCLyl2Ii/I5wqYDquWUyLc8TRQt8Yp2knRboqG",
	"w2EEZprcD+Z8YH+tKFN7u3ogqbBQf9LKAJaMrke3jZx2P/1eomodSqpZLQBrTD2t9yd+Yit2c8jZjM4j",
	"q4TfKwEbD5wFpqSZmh6ZSH1oObokYkkVQQdnx8MJu9SckEqEkdRHg84oyfUiZnQOIPTG/HR5eaabowHK",
	"6WxGhEQzwZfwbVYVBYJpEWEmMGF3C5otEGVZUeVEolLwW5oTgSQpSAaTwyxHGc4Wem5ZOO0hnN4mxS7x",
	"/RWsxLLZGa4Kley/GKdtXoXv6bJaBmRluulVC6IqoWGTe6xZgOnf3d8lz0nRGCeZ0Xuid6tny/UaoJce",
	"ppJkiI6oWhCBnkHHZ4BGafkOvyFsMMVSI9l2ThEXCFsQDC+JQS78LUeZQa0c/a4/PYyG4RL81DpXE78l",
	"osDlFQz4GN7eeXzZbqW5CHVXNCXqjhBmUfk4AiUpscCKiyYSJwx2toVDffB8B0AUrMjjprFYC6J7DWMx",
	"Jyq+1M5aL6FxyHnMMktij0tzhdElqoUgcsGLvDHYePgijZ3IHFid7wOrfP/u3S92h9HWeDge7AzH2+HI",
	"AMxwcb3NBccBSzGTB5YS5xDn5rhHRTLLOtZLZDWX6Wd5eu8U7yItqVlKwdkc5TyrlvrSVAusECMkhwM5",
	"JUiWBVWIMsWRXOKicFsgh8PhowwUZvWpHwNaoJMgQvqZ/Z5onkOuFlQl+zNcSJImjrF8DG/GHb3v+uYa",
	"N++VsUOGXyOwQCqkMjPXE9fiQwDqewtqpwnq+zgsSTLO8gDYJ8+S7GF/aLPHYE3tPfp5QYATCSKrQqE7",
	"LJEk4pbkhsVAzxrRU84LgpkeIWS3UUHICFCOJWwm6wChdKScBsttXtoN5oozVeGiWGkWm6OtJV7Zy8is",
	"xd5wJEd0hma4KLRCg3iWVUKQfHsTrtkiML86M780QHSU7PzRam4PLulVJSLr+3B+4iQfdyWT5ZTkWgsZ",
	"+ZtF7xfNSGP+C6XK/dGo4BkuFlyq/VfjV+Mk4BeVoDFGaXW8q1JQLqhaNdhXVOFrztiqkcj1R1zoa10z",
	"NLNHBcegQ4E4yqEbLlBO9AqQLEmmxQshhxP2Bqa6j67tnK71Jej+2Dc9rq1MZvvbmQLzuMaV4tdDfSM4",
	"3ClBiUSEmf+CeKcnpyWNSpLwpOJbTAs8LbzS+29mhAnL+HJKmZGfgFtJr+wsiFkjjPnttxYV8ttv0VZO",
	"So0VztC0okWOFJ7LbVCJruf8Gg3QWSUIesu1XG617S1c3OGVrKeSosOzD0irhCmSBb8jUm0DBL0pGgbc",
	"GOcVU3RJ0JalU4kGerAfJrB36fvzS60VzbBUvv99gXX3t/z05Bf0y8lBpO99gdNfTg5018uzD6PDD68P",
	"RodnH7bNSl8DbuS335oVAeLRAB1Uig9yokim0JQ0sLpld8pMIKtymMG7fx6/Pj5AGjp6e/bBfOOCLAsA",
	"V2rx6JALcnqiD3f2/sJiA477dAUIMBBVWZkl8XlB9JTRlmv0y8mBHdW0ecNFRjxqzYKOzDnyK/posGf0",
	"yfsCm3/M+ST5pEFcipWjE2kIW6OgJkplRNoQ1L5es4e3r8rK/GG+ub/8CGeCaDb29uxDCpwLhtNUfmjR",
	"5MECulq9Da5gYhZ9OMtIQYw8PWmIvB/r6ZmDrucG2rKZmP3R/MtwAM/au2JXi41bzedKkqxy3GXdfYCZ",
	"mhWrwZxfFXSKZ1cyE1gLnle8JExzTascX1h4tUByQ0h5hQt6S5oy5otlR8L8id8ZKURxpLs5oUtzKn1X",
	"MLQkSy5WCM+0elhgqTTFoa33RYGXeKDnjRWdFmR7OGGnpjMWBIhAq9iZuZOYBWjAgHkpd5oYnyHKcKbo",
	"LVWr4YR9kMAN8kBTA144SV4sJwnaeoGWlFWKyG290TsL/dsOWvBKwA9j/TfBcz1dw2/11F4H3NEBKvBv",
	"K98GFfSGILOsIbogyrTU0BRH5L4saEZVsUKEwSlujKB1Os2KNXUuayS4RSujMVclsFtGbonwKBk2SdBs",
	"UoeYCj5/Kr0UfD5vkYulD1AYOYOrn6krp/w2pfUNlEcPIuDcXpPGhWbTenkHeU7tVee/3lF9jgn6XJGK",
	"5KgqNZL1vOCHK0l/I8MJs7swhiu0YgXVN1leM9AW7p5HFVZ8f2UwfWV25qnLtPvpDkjnZEi6rAqFGeGV",
	"LDT9/rwgzJA4TNjYT7VslKdwTxZEnyJBMsKUk9eMfEBlfVK2Ts4/IM1E9cS2N0EGes80ec5mmuPeEi0d",
	"MFTzAg2dcTb4jQjeQtxeH+LMEq+W082QZjGyRRk6/XHb6vswX7sog8s4jnBZCm7R1Isic66Cs/M4Vry6",
	"xRDOb6nUMzSDDqzQbOc9YRWYco28IrXAYrZFU6OEo6ulakWWJRdYUI3s+4yQ3CzkFheVJtqfubjR5M/Z",
	"XNKcoA4BWj2ekcFcYMqMPUkJXrTJefz9y76NqY/JU8k5NHUBFEMnPTwhIN561+yx1d9mVVGkiJG7Gq7e",
	"NU1uL8Z76MJI5+gDq8UfuIrPiRKrwQHcBguCcyL699IM9gid981/Uo3HewSNW7jdGfdbt66kEliRuVNQ",
	"PPs6axmKzTsQXARJmujbJEmTKa9YTvLoc1Bzb86IGDT1AjvwCuxMguZEDtEpLmVg/IJ9UwtCRadXfQEz",
	"rlmyfcXBJZxCvW0WhfU4xtLGQzYBQt/xLPjFoHDsd8Den9v7KLxA0Zb+h4aVkyVmeWpPqb3yaV6Q7Q7o",
	"H+CC3W9ephZSfWumjSsT5G6gRGcUXGi93S1pYjZkkoQYMIsCNtO9k7ewhAcLfTpKQewYrn3ztk4RuSWs",
	"zVo9hkrKWHg5wFyBAcF1KNGS3usVmvVqjgIotHyBmsMl8ZKgknf4we/JjwcHx6PpnAzAHDQgbHC7M3yR",
	"7HsaXFKhFqNswdnNarDUR17ZtvAGU1A2r3Ax2En2DbnGLGRmMlc5jTwU/IglQTkVJFOajWq+hSmrjRCy",
	"mrqvVBOvUz4xaENUZpqwpVvvTPCl0TF+rwd9GBktnwg50vL7kdP5vT2w1nQa3bwlWPdqGkf6OwkicN3r",
	"HP7aqFvG54z+VneEv0FcfbTrnaDKdbwgn3cvyGfkfm33bgqu/3s0VAajI9dOEoVuKUa3tCRie6iPlz79",
	"kqgUdDrQudWAspblGG5Ex5PbMmhnnJhIqil0gxvo3Xp5saQlKSgjxsJsTAjoCGcL/wVOrJwwjDJerpxJ",
	"CFqmSHK0oPMFEeb6lcDqllwQJ4tMK2XOHvw6YcEk3B3hpf2xk1hCXrm1pGzrXbU81Orn8+22zLkTu0Ys",
	"F+menxMqlZcpa35u2zeYUlTBulwQSSIaBl0uSU6xIsXK8CZ38MxLXYrwLadwiMDEM7BLRwVWhGX+5rAz",
	"kgteFVrYUdkCqQWXBDiaJ+LghKItMpwPtdoV502TRE97c8G0qZTBmG2Mf+xjg2kCqg4dZQUtB7dUwUPS",
	"oNTL2Nt9mrJuEXSl6JLwSjX16HHSJ2aB9UlxdIepAikGOyqDpwCuV6BIat/+9AqtCKbb685r1d+9sTTG",
	"jZ2l+S+ouowjO8sUBYrRuZOAjIwKL1b6IrJtAzHtOXqLFbnDK3RpvrXZwd44ygDk3lUmSE6YoriQTzZn",
	"7NWaaQClbWV25uEek7L3Doi5AATOCMYIW/sheEsy2gJTPReILvEcHulr34i17iXkXjXdE9a3P9bgP5yf",
	"NPp8ekgTuOB6X6QoKysVc0wqK++hAQYKDSX0PlkIQlr+J2zuXDucE8r1JFmQouDojosinyTXDfeToKnc",
	"BzPbwjiRaNqzPT5dr/NYqTG+rQE86qRi4T+kqNEUtkaTgWkf/LmvG9p/TZIcK7wPX0clm/9/+vi/fJ4O",
	"h8NJ8vCgZ9rkI8HStewE7+2gngst0miS63eTaeMSbU1xdnOHRY4Clv0U35kQ273QNuZgvcMEh6C1WY2D",
	"IP88H52e96t3Wsy1t7m7UOzFGDzwt+6bBl/qvQe6yBEVy7BqiipKVKTz/G0bIjh3+mDNqLKzAnTdK1QQ",
	"NleLyLtgi3W5dzFzhGMMzB796FOs51Ay2f/4cTwc7+zupYPxcPz8xct0PBx/9+r7T6n+fXfvOfz+4uV3",
	"+vdX338K3kR7UNR5JA1H6yWdmmnegogv0RZnBAQ3gy6D8Abl+H889ljfvYM3fAc1kguYiDST95P8IlLp",
	"2cIAPdF9FML4c7SQ6n5uThhaO+/KR6dggMRGfUMZlYtzgqUG2x7F/I7uFis0J8w+dyCpeFmS0I1V/5Kk",
	"SU3UtdNm/WYxo4UCBXNWMTBIQouojeONbfGazKjRiLpzq79pssLIQTWPihlmaErAOdS8Wnl5v+P61ADb",
	"lQCCv/VAdxq6ccqy4+WcNFx2krfEtHA6wh3B4CFAGbhrZIDFGIfRknPc740FfK5eKIf1NcaeE3Vlx4vq",
	"W1jgJdGaY79VKsbS/uPi/Tt0AcwaGeKxeJkamTCYVTBEw+7QRLpHQ9zNj6oVWDakwlrU1foBusAMvRGY",
	"ZVRmPEWHB4+SvR8kRvmdHzSQrCmlW/+VuMOHFpjYDB4/Tdd66VqRpHlrn/tYPOx6bIZvzZEjhwtOswgO",
	"Z3B2r4Q/vOtu2MZBf9AXSk7uYzJhTu4NpVGJMhjZ2ZQKKlXUX7Pg81LwaYTtn/A50p/wlBZ6TwOvWa10",
	"+Md/kqfIPtezqgBPcP1fPNW0Ywiya2OqfeLXLdxh0bnQd5xEARE1uLSF1/U7E/UcvlCC4KU+GQHXtJ63",
	"FxdHYP5TSAua2x1uZFDevPY2WZ7xJzOUEns4FgQrkgdSX8d/uMMs/F3Z9Xw0mAgM2NkCq6HVTSlnQ+Ox",
	"9mkjD10LrZ5k4A5ksfHoJvSdkZwUCm+Kw9fQ+CH9k05WG9E9hGemuG6Fr90i2jdgobAXwMED1hFel6z6",
	"Yg8u+Q1hHoiZS+/hqyngi0JH1oVwmKFlcxl1NIl8asSG38tO2EYvmjcJsuneVfaIk9zHujhkbmksGkNV",
	"jQJEJSoFkcREofz1iG7GyhitxMTJ2GmZGTeOAHhOeuB/YfSM25pe08YS38eckndfvOw1rxlfZMX9zoVy",
	"CnSMvOmZrZXRgIBbIqTh8a6Zi1oJLK9PjloJor4212NCfdguj/cpxP57SyOeg8/XaE6WSzzYG+xMB1RF",
	"TXdwSh+Xl45nCGgbTAQUXsqlfSOHE+/cOID2sET+hpRRt1lFlqWedyWamvhOe9wLvSBgInUPcARHP4BL",
	"mVhqElc0S535/wdj9ReY5XzZchX/Lt1E+4Qz4q+iR89GfV1zHju0ztQPn9GWk7HldnB2taajj6UzkXuJ",
	"Sh9xa+WH5/I6gs8sxAeFOP+hjc90VNHm5dXNIzEQl7wc3CDp9mXLu+TeK8Ik5Sx1r8426Ovg7Dge8aRH",
	"K9dv/7sqK0gl6+ECOTTZyO8/psR7RrCeW9XWmOakumwhA23VC042SlKSdYJhnEgCILYt2rIqaLFy0vXO",
	"xgyopX2slylbXteM3sMbgVR4WaIt43Avt+1dqBW8eq53WKJa8KvfxL4bP9/Z3Xse58exiLcDVDH6uSKI",
	"wkPAjFq3aRP21sByg9/pb9myLAZ4mu3s7sVY3WZWo1rYj0YLeZm5K0NYlVr38XrQpC1TT5LA4tL6FrWi",
	"VE9Rjz7ElaMN5XM32LpT8aFPuHKLaFzk8edfe3nTNhUl8RdUvizVk6Gabj1sR+GiF+Cl/uqAmQgKAwv9",
	"WzDVGENrYb058TSCotZUYmh3b0URHV9/QRAaIUALRR/Ojzv8pj+eou6EtnpfS5rRIPFm9J8/vj+/G//n",
	"2znfJBqp7wkv9irWs+hQWQqe79ZJa62nNPds9Ni58uj3jLNWlmsgjyrI8DWN9qgRAHzo0g7SoslVCQLh",
	"6Ym3fnqfM/sgkugRjQdLYqOS7I/OPwX+ML4lSZp4uTHKdPxcjtmMx/TxNcbW101Tq3G8MlGfBg2hjdUw",
	"FfuKUG+mC5ttvEMZrZIsMVM0Q5JgkS2MfZEuaYGFEQk6a6FZbJbHGWdBDGlRZTQnA0Ew8Mh6im8omxNR",
	"ChoNf+8x9v5ULTHTwHLwc4RGIdCjetN6Xu/Wk2VNKj2UZkcMZ2UR0Ut5MpR32kKL8aeK3NbelzNru1nZ",
	"C9DHNk9MMNkk2W4+vboQs40d1p7kveHfC9fNnbQdyzZ7dVzjfhL/sE9fPXH290pgeF9bN/23J/Td0Tny",
	"jf0W/EYEH8gFBxcP75UGakRWSaXJHk+JMQW0Il80F11WjKrVaF5QRsSVWcnt7nDHhsF0mpiNUljePG2V",
	"tQq7bpW+1ejk5LRvo3q04Y996rBehzChYqO39tv7d+9+eaqLkOOxV9Tyyz5X4bUGIA8GDiSw3o6r8Gui",
	"MC3As7Q2wuOp9eOx/Ws3UudclOHSaE2UyOGEneKy6XwGQRcm8oDN+BB9AN83MBh5NZuYZ7MQ1IQRnC3C",
	"kX0c4JahrRRpKtREmCJBCpivTBFm8o4Iud1xbM1lQZcjOP3gs/Xu6NyE7taDwqMQAE8+PTxOi/2908TN",
	"De5GO7kkTezs+sGHp2Ej+J+iNsvAeXQd6Xc3tk33oRdqk/Bj+EzDXwss5u7nR9f6xGNhPWrXr63paNvD",
	"YB2swe3uYLn31HlYP9t18+hzv+1i2jntNmdaLD/PR7MCs4F6Ybm+/FzhfPB5nqTNr7AP/uMTlhILuzYv",
	"tDWqwyuvwVqb1BZiJSYS/KPSUtZvcCLee0Hvj0iBBH0OYNqY54ZU9BMuwO0+o1K3GADdL5eE5VY1Pzg/",
	"ffl8dDqQBCKXT3EW9Ub0i77irFj1x/oDfzPzQPpfrFgFsbmBLcBfqVFT5peJgG8KjtXOy9j8g2U/MnlI",
	"HRFiyWM1YnHdQK4Md/2J4uVjRBRXbIztJSSMUU0ATl2wms5sbzdJkxngbGr+Q1/B/w3gRZs+h/8bQMxu",
	"TKnx9+sRUzbqtpPwaV1GJD6bSeLSHxGAEcvsFEQWRZ/Z9d0QcQUy8HR7tHV2dJ6i9+dvU3Ty/jBFp8cX",
	"h01N/AzYddeYn3FBetIdmeQq0MLYzxVH3Vwq33+/iYUcfMmfiqopmVPW4O/jp6WNsnBsKqgaGf/BFwxd",
	"LGnoibcuFYrbA7cOyCSVOOzFCNlTTu8Llr3xuygxcradumlloohBWEdbVni3t43mQdsuvK6S+lrEKGyS",
	"ohWv4LXAJIlYIcxWHjOrkoTQ0wmDEGUNptYFNCytA2iR0Yh8gihhgneGE2bDRmwqKhuoCu2eSR8KYRcC",
	"EZiyE7n8MSmJkMCHwBjDVsYCk1egXOdYkafd4I+8k7Xlo43Fox7pKMKRjWx41bfN57ZBZwvQ1qxWyEDz",
	"euYFzWe1KL3ysRFgcfQWdhdLZWVq19VBBwccRx5O4E3R+dGPRyfba/fSQYBwtFowR9Q43ZlkDZ1tndmI",
	"xjS54+JGXgF3AP8skl9R9rRN1WdRxrMlNTAIxK3ve72rzfnUJx/dmVhbZZNdDJM0MZkyjlk21BclZeiw",
	"ghPL+PAPSF3OAGem/wi36LOouDWtc7E1Zxom0XGv1YPHnWs3UjDtBfjlnrbu5C2bbyePHJ91y/WkvWbB",
	"7ow0XBwclzRTWXPE1p6UL8ClGeJxJPY5EjsSWEtC4tDPP3K51GsDd1nc5YSOdUDch+Fe+8jKGiETeXd0",
	"vo0GNVeApiRHssRMmoQYDaFEg3PK7X4da4LFlCqBhb/qcBjhZzLyNG48CIv027WPziMczuXV84ygdyM1",
	"MKu776MjC+EWgtSlzaaoP8JrQRvGtmF2Vtjc2EKwTs4M7DgR/ajXjtPdxu4zcsPg0PuWHLQyCkMvfbSU",
	"2a79In0iiwkJdyP/rXMyp1KJ1anjOK3kYCJbUH0pVaJXj2i0afj8H51frknzFUHhhfe/oO3Ezxs7sblc",
	"0rFH97X7dxjuG+Q9bhuAkj91O9L1qrxBbvMtofvKEvcg+Fw5gaN+z29szUZBO5RdCUse6zRiUidPoT7w",
	"9ZnU2gjNKCSdsUC+WI+vLaZNAnt7hC70KtARmxdULlDfUuow6S6K4VsIdve78WnTFb8Lj1ci64cIX11o",
	"7k8V5AF6gzOCSqwW218YQ2Wg9ufqM3kpHIcxE2xn5ZP7o9HCzGeGMzLM+OgJQVxPeyNLk1ssKGZqrQWw",
	"YZ7yHTY8aF3LySNiAPhkWDryKAoQmzpbS/PchfMKDsWnNQy1XwoNsyA1cFIUgQPaUzlOyMYjrCZE85Wx",
	"V22+La79F+yKtWL2iGuy7wSBQWZJFM4x+FRvNG7z+XwjidAdbv3fKIriW1zguG12QUzSgSeqAz3GqcsF",
	"qYW0BS27L/m1ZvjFRinn5eU1gTVWqhcb+XFiWjwZB629ATxaUIHdaI2lSOA1WYUfNWQ0HkMidgyXoyTO",
	"uVuvJLHQMXBKilD7mdDdWU4EyYNExE4ZN5CHCOK6CgqZO1wxCOl8bbzQzuYThlmODEAapjaeUVLkcqTI",
	"siywIhJNyUzvfoaLwmcmICwvOWVdA8QxU8aMZCPn2pHaxgHpNWRnsz+hWcVyrMfGBaRLfpKR4nNFYjLH",
	"hXE+ga9WQivILXbE3I45bU8T4bIsaOa1ic1CT81c6j1cR39rWf7G+rynx95zHbeFBagggSpvJp6atEY2",
	"6aw0Cn7DmPHUAOEefNkJxtEEj1/rcy3IvmQLwakAMCMlMJN61k1qvdQ/ayrXbd8SscRsH0VqffypxtD4",
	"Q+aG75iPPGNuRqcWeWvx/mfRpwbXQ5899kUzBUWY3cYt7ExQxvKUooblKTUWgrIwv00JXsYNb4/bO/+g",
	"VdGGEEVuZl4QEz3tYjIk8F0TqpwFoS1hsPdKKrIEl1/QyHxVHRv4HbVstDOdxFPdR90zOyaMNbny28lM",
	"1qkAbj2tJPfrHTF7M+JDXETEJx0i2HzkxrYxt3WjNzqLdD0ejT7shsoHa+xuubIOoWZedXwAvGFP/LCT",
	"RN/SXpTfDl9T3cw2xVmkQxNvECPWhzsIDuyErH0xvtx4Dm+PWCA6sQQ2Eq4beQ+RNf0hBBvuCKx23bZ8",
	"2U7QvFYLN9qOnpDTY5YJYiSiYL7gDr4+/vRLt8eHcW62RyaQERLVCWnDWeuNg4jb7biZ6LFo+LCymQ0U",
	"MPw4+hL9lM2OTHnzTe7dwDcBwrvT8NkaNkmQgcUcJPDIlQh5IWzyIosm39oZc/wCwtPy+8RnZzBplzrZ",
	"HSbJw5+QI8Osb/MUGbHcDGmAgU8boHyDs9OY3ybnZ80ehHBr5Ac7szka3QoMLvsoc1Mq9HGQHfVdCV5I",
	"EGTrm9AUkOC8kENkLC7m6WmS4EpxTSTOmpzRnEh0V6fhACRie6WFhREmCeOM1H0h1JRxZXuwlRnQNHX7",
	"XjdfVtI1VTadtJbwdB/dxSx33xZAwK74RtbI0OKT0LRK5rnjrReXpDDPJKC9T48n/dps2LWcuPnli9PP",
	"bHCG+jOw/P5VBItPD2nyTyIk5axfZYBSIpCeMZKl1pQZcUGMTeP6ePf5YLwz2HlxuTPe3xvvj8f/f9Sd",
	"kKqrjC+XsbJBbykEJC6pQgssFw34Rop4HgXJr27NsiIgObIe6ci1acZ17wx3XwzHMbC9MF2Ibgzg7c5w",
	"HAPX2qy6a4CPNER+Y1kxSmnnfXQhI3X2x79LOP5dwrGfXnrKWMTSFc075RLhZva5cE0yetmhl4LckuKP",
	"ltc4ASCwS6vH0348Bu0CgETv580m0khYC/EpaQ/CbomYapJZIYOHWnzNybSag2kHut9hUyDSJaSruYlt",
	"0GFNm62yMVUTdIKL3unySpWVskGeCJA9RM9cN1NNMuMFF/Q3U1lB8oKk6NmvkrNnTlKrwFsgB0krRc8K",
	"Pp8tlflqSlASeDwmTKEbsvoBckujElMhU/SMcV66qpUFYWoYoCyY/q/GF9LABjGBl020BY0fRV1Putyu",
	"x0SWESmvbsgqWuz54OcLZJrohaHj10HK2BuykooLguSKKXxvAy8zQRQqOL+pyiF6A0loXP2lg58vrg4O",
	"D48uLq7+8+i/ro5fI8JuqeAMbP7waDktCKI+JXmzOOeKV2JgJjO4IasBjZp83KtAhMfuhVG/rp179n4m",
	"94Z4iX/jDN/JYcaXzxAXeqtdUbjvx+Ox2cZTyo7fN5/F250hVJGdmCSJQdLvwDAOmLqq8R9HvkVovQd/",
	"dAMujg7Pjy6DffiCTTCDBHsRtfwTKX0Yeyw9hq3xY1YpjTM/ZKiCY2WrpqxQkDP6SWuPTRtGGZgZRbMo",
	"kCspi0ezvh6Zkk4XFyejy5MLGPtiT/MOZoqXSa+a7EM+HBOX8vMF1CPzFW4yXNSkFEkc+Cgn37DCV/fM",
	"m1JLV5qsZcxVhipSWO8w2xbptpDtfXR8ZtyNCspuUM7voNKFhEoCZFmqVQrOwgDbVPayELRYREqFSkFv",
	"sSJIw6EzNC14dnNlf7yipSndKSqyPWy+k9h/2tOV5WzY/GXn+93hePjk+DOHjBKrxabI0G1RKciM3hNX",
	"nqcg+6ORCTTf0//6cH7SQQqMESJlqBVK37mSBOGp5EWliG1rmdPogyRCjnKs8GjbdDKj6C7TKrshamTm",
	"43osVwP7e1XCBo3a+AxhanbV6fA0PHb28dFT9KPu0agvVJMGEphBcq2d3e+05jEcj16laGcc/Pu73eHO",
	"S/hrZzdFevd3Xr4yf79M0c7L74e7L57bv7ejvlyOeF3W/iubvKYx871uaiObEV/vO2U5vaV5hQt/FBAv",
	"bWoYcDBzMMPyWWO4HehSywA7fSWb/Owk/Y1cTVeKNCe2M37+6sV3L8e9NZx0P021DpAtHGXqaSADsBGI",
	"5OH5yY0f0TUoUy+fuwmbxBU5XZoET80kbePnr/rmCf3QHc3VYrQgdL6A+ZX0HsLTbVYHlzlMEL2sZgFa",
	"A3wdRrvc9OHByqk25x82+XqMXSQ5AE6bpCYzindFm1O1qKaa31iBPJ+ObOGTbgy2UyNMKTFbngN8pA3r",
	"r11GoYaw8IWsbT1zl8ZDQonUb75BPy8w+FNYwGGxVhu7Id2tchJANzU2/QwCEejg7BjMbt9+WxfNeesT",
	"G3377T6ChzYoZFZngd86PDk+2+6kQzCAoIMrpqMhXLhMHD71A8wnLNjtqpQPgGBdrWEDz1fY0bBqnwFB",
	"BtaDwl784GhhyjLbmbzDS5I7J/ag3o4GZJ2+kQlAkiniYo6Z9aWSqU/cHCQYCZZ37t6TAUPuUd+ozCbO",
	"wL2uuxQL3rO8ThuVWreQ8BeisqGp4eNYCaTixYpAcbuCYH1BKOTI0dDgkPJRzjM58nexpxfIRglR+hGa",
	"yTBDomJas2c5LjgjUDi/rm2FGTLnAGVFJRURQCwnQGH1/rUoTTNGcq+IANHu7NhWxyMsg0QAgwgZXo9w",
	"SU32jOtaLG+8C0NPT0p1sWxHAOcHb+vKQLptSCrOWwr49VIfFZI7kvlc4YKqle5ySJgSuAA10DqlEnEL",
	"fjiZ4FKinOrbb1opkiPGczPQmb6ystUAok1M88bpg6xJtihYQfAtkUjLorqFwF6z3LZb9oZA6kK7g9+g",
	"2Lk0lGiysWgKDI9So26WK0veWy3LQDo4OwYwm+2LO5bGzopM3WmYx4+UaXHdG+VT0JbdSk5rBmJleMtI",
	"DECTsskvFwDqzygogfgr0IXe/IG5MmoWJEucEQsJnG/CeUECKp/HSqKt695MVtfb+gxo0c0As8miDj1S",
	"NMAPkshWLQxrXdi6/qIyJLbgyLXFhT6vh1hCRWVkEGOoNUVAiAODRkGUoOQWFym6pVJLIHWGI4f1Bjtu",
	"E86bmun6w9QppL2N/i2ksAAGem3pbKWBHfRWbOstu2ZgHYLXG/DS3YEp1IsuL09cPS4oEm9avrE3A8y9",
	"ode2S5U5F6AZpoU/S/4q2XQN4cGKLCQoBWcghn7EDlxQ0lhTjfXZrauT0lmN6oB+dfeGryWwPOvSh7as",
	"b+UCs7zQCgglRR7EQpkgpYJmxD6FOKmmKNC5lq8kOgduBU9GTRGnvlMKMsfGN5sq0KHdxXFwdpwEzwjJ",
	"7Q4uygXegcyHRhNN9pO94Xi4l6SJ16vMzoM2ymXMPFMWVKsBeqWUKY7AsYwIs6/SXq0+s1dTamgllnIi",
	"06klWkMBQPB1qb8urZuyR1qotGY9I4lJPTNVF+K/JaLApW78wVVX+8EnrtI/v8HSiE2N3LNuGkBXp/44",
	"dSUkX2XTMZnwYA/Q6TpeHzjvNU/ak08MsidT/3VuJCtQXeFEhgWNNW/edTW2h9CNgLXQZ/WacrWwhnZA",
	"iwr8t9xW2TLy+q/r6+tfpb7ofp8w1Kj35GvzmiLkzl8YGGhqGpthDItlCOmfYGkGgN2k1H1SWMyJS7+o",
	"m7wYj/1Hu9GNr/6jJCWGrB8G8GTC9P8S/flhwh5gFeYd2KmDxzm8u1Ts5tI8cljV90eer1qpxwPP39Gv",
	"Ni+9eQp4PJd0VXuWPzSfWLQSDj+YyxtO5e54/GePbZ9gYfCY3x6QZY5kBebDWVUUYEB4/ifOxBTYiczg",
	"mEG5Dmd10OO++GvGtSKx1fWIbZgmslousVg50ojwP0nmxh1ENzfyWD8XdckSZSxbIneB0o6xGJ5atER6",
	"ObRFaL0wTmVQV8xqcCAvPpNNMdEKQsaCe69S4+EPSZ9zyBtg+nZycAb6pXVEBBiBCNhl6ad1WctHeWFY",
	"I7aummmrJ2oty6zC9Ai0EMWhFEqQ8SeYjdMIB+A8s7SClbPAxQPVtvfRQQZ20LB+mxVJaiS0gYGo3Oyq",
	"EWuNI7cU1/KtxVNDDjZlhYMKf4A17/L5Vev9xUqT9tcA3KjsnxGYv07Rv0iG2O0/eCEGdWzhJSMD6d2a",
	"PTWEnOSVYTkknzAr6MB2zAqwh5mar7emCm1esRwzBcks3KloK2T6Z/9W4n3Tvcs05B/RVGMJypRUN7WV",
	"Q+7HM0XUwLiqXXsVTxJBtaJsA7CswpeiJZcK+ZfQ7Q40zUuv9427mruEDEMIUgwCvwj0/lA4MHSsqS5M",
	"6Nuhrv2uCBGIAH2FZ638AAxSt/zYon1NVO0QnUnyqb7rJ+w0WjC0S0/rJ7iuKm1smiCQPHpmMCoXXHET",
	"ApBhpQ9QpOsfO0U2y7M9TBr8pzWykLurarX/KwlFjZKpf7FQ1KzZqMfuO2BNmK23Ejh5A3fySN4trhgW",
	"OphC84jHTUcwqXEfVLf5VxHNno+ff/1xbSVrriWOyiRi+JcRCX3q66CgJEiBvp7NBoJgYJg2kl6QGteK",
	"F5DVFu1tDyfsjd70jrSnRSRbqONwgRU69GnqJTo4O/5jwlmQj/dPlM6++Qb54mxwHRKFrs1JM6/y1yY4",
	"z5S1voBNGFzo6/EIKtJA/bZts3xa+11PmHFSMBVtbO15czXDOxJlWj291liqkQSi/bX1IjZ12a0DuHEZ",
	"hEGMWRJ9fP3+3dGn62FEjtM/gfWxp7aIlb7NlerqE8EL7fobJ5b32N80DlDzshG8sDeGiREz14U9MebD",
	"f/HK7D9akKKcVQXy4WPDxu1Tw6okERFIEA35/0wSc6O4eflyULrR7ouX9neDV/0bOFuE93MtSaCtd5wN",
	"vA/+tjU7TLFcTLS0VqDBL+js/cUlPLbsj0a1H9Cr8asxkKM7g2gy0SMPfkITV2J8cLkqyT5qc41J4trm",
	"6FnMPLFmIzpbsQni3JNhW27590ny8KkG28DkzngMRoxnUbRd/N+OMk9rNX5qitJso4GcXpnm0Du9fg2B",
	"pl0r7S+WaTrFjx6sG/AIGGFUntm4sGXsrjzsqZw0ROdEVYLZGBiteLHwXHs1K50wLmJMvlmD0GtlW+FF",
	"Aanf/haD/lIxSI++9/VHfxuUujbu3qhitTixxbiTlOoKatt9QlogaGkRK6L4GeGtzqgzJyoWe25IWos2",
	"EvS1bg2K1Nvu0/qFO61TUafo3dF5ikx6jUaucm9vdxYxY8nqPnbFrWe67T/8K5ZLNIQW+Jag6wF9dY1k",
	"NZvRe2cysW8QZpCDvmofaGta0UINKAOrwVlRSQjZWjur8H3DGkHsi9wGS2q93h0tS7UyTq/dDbfg33ox",
	"1cBvV5joE2k3hV+nYdtsAXW2Whji2GG1mSxYM7hoiQ8/qk3xYMZsua5EhnUZIWDQyxcpenNy8G6g//Hj",
	"wfmlobmT03+8RRGvF/+K3FAQAt1AS//2HFotAOAZE9swct+eUKlOXWqkr3bhtWrf9LFP6R7l/7t06B/x",
	"v+bTxklMSzPM0NNxvyrrD4YEE2Ee5Ph81IPLelUFlaIMg4azFRa8aXFH4zemZVJjSwUnKZGjQ/7u5KSR",
	"Stu60J0dncOrPUwI5um160mQgniSWC+P9+dvwe0mnHfdweQnNuJpnaHYdz55f6g7n3g/Nd/xHblD/8XF",
	"jekKUdbEdzs9voB+p1RmpCgwI7ySHpsdHb5+at5Ei+8wJG9//ty9L7ag4xV9NeSM3cP0DlsmhzAP4Y9H",
	"55f2Mb67Z7pzk+e5J6Qsllf9lmJjUzB/X9epEx9/iQ70jkhScK8yQ34Wa0Nek326vb2dBNQN83KH9TWz",
	"klHytaynnbz2f7G20c2UHbNjOpZg3WD+tmL+TxDfA7/eL5ffPX21bhd3P9UpZdeK60GVUoIyrHDB5zZo",
	"pJMn03A4TZk+a+TQvNGGr+7eq7vOnJBTAdb+lXnvhRxXNqHHAVMzLJbow3E6YXVNr2U7L69MGymf0+Be",
	"jiY3TScsqDNtsxsbMc/lZYDyXhtm1YV1fmDgCH/tTbp3CwoO3AaV8J5eJ8axwQumbdpM/jdhrhPkDjLY",
	"hcRLPoy3roswxyIviASl6m6B1TMZjEKZVJBGofOmeuHcdN2j/9L7UPpH7A132fQHuQEu4jp7aO6TOunb",
	"3CpcTrnT/7LqjncT14BiOUBhWmsTo6Kt2d5uimY7L1NEXwV+553LLzDudYx6OzvP9/bAque2Fv0v9Ovn",
	"fsOYOq8TK3/Fy6KVz7aXV/pZ98vs/0LvQMom5HBEXmeptlxKk8k6EXpg8yyWvW6l3u2wTlOpOMI2UKEh",
	"NjersbkDc2jcUs9dvk9f/s88eFiv1WUl1f6E7Qx9GIYdz6X9NKKl8+2TE7Y7ROcmVx2kcXFJQSdsb4gu",
	"CMsja7JeKQhLdG3Xd+0ZbE4knTN0Q0gpazahsCLAHDRng/g8aacMsWlGltS3RJ2vtOBzmg3/sNzcsERE",
	"pGb3Vmd6XfkPIDsbr/Gmr3EpyIyIqODddDh+grzbkz7Wy7xAJabp2kSmvoPdluBZadLJ3HpqIZ1YSPsI",
	"NnBe0VxftrdEyNr3UwOApK6uNXoTJHXdR+9IJXCBGFFWEBcEOrfcFCbsDRee/LzW4Uje8PSWx3UKgZjK",
	"E/lA0pxM2HVBpyPfVWsa2Q3EusFt59y3a3p6PMttWwPQoM9sptevJf2HuYr/ctG/kag2wj3t4t09+bfU",
	"/z9C6neH8Q/I/BpEffWt6kvPXahg51x3o7ay+q4LAIyYSUHo+uN3R8Ma2xoWjPKEZTwnAu6KFOUE/hpo",
	"UdP+ZOIU6kYQji5jFpkNrLrffIN8+JKTlv/hejRjS/2ziYNoL35TNGcAJKSlE0yF9IDEqg+KrJNtuzJg",
	"oQwBJjoscLkQWPp4UsCec7lGOZ1B2B64VuYuotWmZ3YRsXW2Zt3LVR0qMJtX8M7cuVP1bRJDWo1Sg771",
	"LhprUi43fQKd3WneRu8+mlTj8V62KOC/BP1IVlwLeT0/S4UFmOQlOlIKo/8AkyZl6BDntChwBg8WIpeP",
	"mqkAy18x5qGVp/svv6Oa2ar74h6ETyn99xX197vyRndUwJ5i94q5qYJ8fmvtU630fima+7SEKZr6FIjm",
	"QujmFxzGNPp/+nx/X+14tTM7RpBtm4RJ/v57Xtw6OvttbGbQDIhSQnrQeNqIg7NjS7o+RnOES5o8fHr4",
	"PwEAAP//DgsJ1ZrGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
