//go:build go1.22

// Package termite provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package termite

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/antflydb/antfly-go/libaf/chunking"
	externalRef1 "github.com/antflydb/antfly-go/libaf/logging"
	externalRef2 "github.com/antflydb/antfly-go/libaf/s3"
	externalRef3 "github.com/antflydb/antfly-go/libaf/scraping"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConfigModelStrategies.
const (
	ConfigModelStrategiesBounded ConfigModelStrategies = "bounded"
	ConfigModelStrategiesEager   ConfigModelStrategies = "eager"
	ConfigModelStrategiesLazy    ConfigModelStrategies = "lazy"
)

// Defines values for FinishReason.
const (
	FinishReasonContentFilter FinishReason = "content_filter"
	FinishReasonFunctionCall  FinishReason = "function_call"
	FinishReasonLength        FinishReason = "length"
	FinishReasonStop          FinishReason = "stop"
	FinishReasonToolCalls     FinishReason = "tool_calls"
)

// Defines values for GenerateChunkObject.
const (
	GenerateChunkObjectChatCompletionChunk GenerateChunkObject = "chat.completion.chunk"
)

// Defines values for GenerateResponseObject.
const (
	GenerateResponseObjectChatCompletion GenerateResponseObject = "chat.completion"
)

// Defines values for ImageURLContentPartType.
const (
	ImageURLContentPartTypeImageUrl ImageURLContentPartType = "image_url"
)

// Defines values for RecognizerCapability.
const (
	RecognizerCapabilityAnswers   RecognizerCapability = "answers"
	RecognizerCapabilityLabels    RecognizerCapability = "labels"
	RecognizerCapabilityRelations RecognizerCapability = "relations"
	RecognizerCapabilityZeroshot  RecognizerCapability = "zeroshot"
)

// Defines values for Role.
const (
	RoleAssistant Role = "assistant"
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
)

// Defines values for TextContentPartType.
const (
	TextContentPartTypeText TextContentPartType = "text"
)

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content The message content
	Content string `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// Chunk A chunk of text with position information.
type Chunk = externalRef0.Chunk

// ChunkConfig Configuration for chunking requests to Termite API.
// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
// which includes provider selection and caching configuration.
type ChunkConfig struct {
	// MaxChunks Maximum number of chunks to return
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Model The chunking model to use. Either 'fixed' for simple token-based chunking, or a model name from models/chunkers/{name}/.
	Model string `json:"model,omitempty,omitzero"`

	// OverlapTokens Number of overlapping tokens between chunks
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Text separator for fixed chunking
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`

	// Threshold Confidence threshold for ONNX models (0.0-1.0)
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// ChunkRequest defines model for ChunkRequest.
type ChunkRequest struct {
	// Config Configuration for chunking requests to Termite API.
	// This is a simplified config for the HTTP API - differs from the full ChunkerConfig
	// which includes provider selection and caching configuration.
	Config ChunkConfig `json:"config,omitempty,omitzero"`

	// Text Text to chunk
	Text string `json:"text"`
}

// ChunkResponse defines model for ChunkResponse.
type ChunkResponse struct {
	// CacheHit Whether result was served from cache
	CacheHit bool `json:"cache_hit"`

	// Chunks Array of text chunks
	Chunks []Chunk `json:"chunks"`

	// Model Chunking model actually used (may differ from requested if fallback occurred)
	Model string `json:"model"`
}

// Config defines model for Config.
type Config struct {
	// ApiUrl URL of the Termite embedding/chunking service
	ApiUrl string `json:"api_url"`

	// BackendPriority Backend priority order for model loading with optional device specifiers.
	// Format: `backend` or `backend:device` where device defaults to `auto`.
	//
	// Termite tries entries in order and uses the first available backend+device
	// combination that supports the model.
	//
	// **Backends** (depend on build tags):
	// - `go` - Pure Go inference (always available, CPU only, slowest)
	// - `onnx` - ONNX Runtime (requires -tags="onnx,ORT", fastest)
	// - `xla` - GoMLX XLA (requires -tags="xla,XLA", TPU/CUDA/CPU)
	//
	// **Devices**:
	// - `auto` - Auto-detect best available (default)
	// - `cuda` - NVIDIA CUDA GPU
	// - `coreml` - Apple CoreML (macOS only, used by ONNX)
	// - `tpu` - Google TPU (used by XLA)
	// - `cpu` - Force CPU only
	//
	// **Examples**:
	// - `["onnx", "xla", "go"]` - Try backends with auto device detection
	// - `["onnx:cuda", "xla:tpu", "onnx:cpu", "go"]` - Prefer GPU, fall back to CPU
	// - `["onnx:coreml", "go"]` - macOS with CoreML acceleration
	BackendPriority []string                           `json:"backend_priority,omitempty,omitzero"`
	ContentSecurity externalRef3.ContentSecurityConfig `json:"content_security,omitempty,omitzero"`

	// KeepAlive How long to keep models loaded in memory after last use (Ollama-compatible).
	// Models are automatically unloaded after this duration of inactivity.
	// Use Go duration format: "5m" (5 minutes), "1h" (1 hour), "0" (never unload, eager loading).
	// When set to "0" or omitted, models are loaded eagerly at startup and never unloaded (legacy behavior).
	KeepAlive string `json:"keep_alive,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef1.Config `json:"log,omitempty,omitzero"`

	// MaxConcurrentRequests Maximum number of concurrent inference requests allowed.
	// Additional requests will be queued up to max_queue_size.
	// Set to 0 for unlimited (default).
	MaxConcurrentRequests int `json:"max_concurrent_requests,omitempty,omitzero"`

	// MaxLoadedModels Maximum number of models to keep loaded in memory simultaneously.
	// When this limit is reached, the least recently used model is unloaded (LRU eviction).
	// Set to 0 for unlimited (default). Only effective when keep_alive is non-zero.
	MaxLoadedModels int `json:"max_loaded_models,omitempty,omitzero"`

	// MaxMemoryMb Maximum memory (in MB) to use for loaded models.
	// When this limit is approached, least recently used models are unloaded.
	// Set to 0 for unlimited (default). This is an advisory limit - actual memory
	// usage depends on model sizes and may temporarily exceed this value.
	// Works alongside max_loaded_models for fine-grained control.
	MaxMemoryMb int `json:"max_memory_mb,omitempty,omitzero"`

	// MaxQueueSize Maximum number of requests to queue when max_concurrent_requests is reached.
	// When the queue is full, new requests receive 503 Service Unavailable with Retry-After header.
	// Set to 0 for unlimited queue (default). Only effective when max_concurrent_requests > 0.
	MaxQueueSize int `json:"max_queue_size,omitempty,omitzero"`

	// ModelStrategies Per-model loading strategy overrides. Maps model names to their loading strategy.
	// Models not in this map use the default strategy based on keep_alive:
	// - If keep_alive="0" (default): eager loading (load at startup, never unload)
	// - If keep_alive>0: lazy loading (load on demand, unload after idle)
	//
	// When a model has strategy "eager" in this map:
	// - It is loaded at startup (as part of preload)
	// - It is never unloaded, even when keep_alive>0 (pinned in memory)
	//
	// This allows mixing eager and lazy models in the same pool.
	ModelStrategies map[string]ConfigModelStrategies `json:"model_strategies,omitempty,omitzero"`

	// ModelsDir Base directory containing model subdirectories. Termite auto-discovers models from:
	// - `{models_dir}/embedders/` - Embedding models (ONNX)
	// - `{models_dir}/chunkers/` - Chunking models (ONNX)
	// - `{models_dir}/rerankers/` - Reranking models (ONNX)
	// - `{models_dir}/recognizers/` - Recognition models (ONNX)
	// - `{models_dir}/rewriters/` - Seq2Seq rewriter models (ONNX)
	//
	// Defaults to ~/.termite/models (set via viper). If not set, only built-in fixed chunking is available.
	ModelsDir string `json:"models_dir,omitempty,omitzero"`

	// Preload List of model names to preload at startup (Ollama-compatible).
	// These models are loaded immediately when Termite starts, avoiding first-request latency.
	// Model names should match those in models_dir/embedders/ (e.g., "bge-small-en-v1.5").
	// Only effective when keep_alive is non-zero (lazy loading mode).
	Preload []string `json:"preload,omitempty,omitzero"`

	// RequestTimeout Maximum time to wait for a request to complete, including queue wait time.
	// Use Go duration format: "30s", "1m", "0" (no timeout, default).
	// Requests exceeding this timeout receive 504 Gateway Timeout.
	RequestTimeout string                   `json:"request_timeout,omitempty,omitzero"`
	S3Credentials  externalRef2.Credentials `json:"s3_credentials,omitempty,omitzero"`
}

// ConfigModelStrategies defines model for Config.ModelStrategies.
type ConfigModelStrategies string

// ContentPart A content part for multimodal embedding (text or image)
type ContentPart struct {
	union json.RawMessage
}

// EmbedRequest defines model for EmbedRequest.
type EmbedRequest struct {
	// Input Input content to embed. Supports three formats:
	// - Single text string: `"hello world"`
	// - Array of text strings: `["hello", "world"]`
	// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
	Input EmbedRequest_Input `json:"input"`

	// Model Name of the embedder model from models_dir/embedders/
	Model string `json:"model"`

	// Truncate Truncate input to fit model context length
	Truncate bool `json:"truncate,omitempty,omitzero"`
}

// EmbedRequestInput0 Single text string (backward compatible)
type EmbedRequestInput0 = string

// EmbedRequestInput1 Array of text strings (backward compatible)
type EmbedRequestInput1 = []string

// EmbedRequestInput2 Array of multimodal content parts (text or images)
type EmbedRequestInput2 = []ContentPart

// EmbedRequest_Input Input content to embed. Supports three formats:
// - Single text string: `"hello world"`
// - Array of text strings: `["hello", "world"]`
// - Array of content parts (multimodal): `[{"type": "text", "text": "hello"}, {"type": "image_url", "image_url": {"url": "data:image/png;base64,..."}}]`
type EmbedRequest_Input struct {
	union json.RawMessage
}

// EmbedResponse defines model for EmbedResponse.
type EmbedResponse struct {
	// Embeddings Array of embedding vectors (one per input string)
	Embeddings [][]float32 `json:"embeddings"`

	// Model Model used for embedding
	Model string `json:"model"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// FinishReason Reason why generation stopped
type FinishReason string

// GenerateChoice defines model for GenerateChoice.
type GenerateChoice struct {
	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason"`

	// Index Index of this choice in the list
	Index int `json:"index"`

	// Logprobs Log probability information (not supported, always null)
	Logprobs map[string]interface{} `json:"logprobs,omitzero"`
	Message  GenerateMessage        `json:"message"`
}

// GenerateChunk Streaming generation chunk (SSE event data)
type GenerateChunk struct {
	Choices []GenerateChunkChoice `json:"choices"`
	Created int                   `json:"created"`
	Id      string                `json:"id"`
	Model   string                `json:"model"`
	Object  GenerateChunkObject   `json:"object"`
}

// GenerateChunkObject defines model for GenerateChunk.Object.
type GenerateChunkObject string

// GenerateChunkChoice defines model for GenerateChunkChoice.
type GenerateChunkChoice struct {
	// Delta Delta content for streaming
	Delta GenerateDelta `json:"delta"`

	// FinishReason Reason why generation stopped
	FinishReason FinishReason `json:"finish_reason,omitempty,omitzero"`
	Index        int          `json:"index"`
}

// GenerateDelta Delta content for streaming
type GenerateDelta struct {
	// Content Token content delta
	Content string `json:"content,omitzero"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role,omitempty,omitzero"`
}

// GenerateMessage defines model for GenerateMessage.
type GenerateMessage struct {
	// Content The generated message content
	Content string `json:"content"`

	// Role The role of a message sender in a conversation
	Role Role `json:"role"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	// MaxTokens Maximum tokens to generate
	MaxTokens int `json:"max_tokens,omitempty,omitzero"`

	// Messages Conversation messages (OpenAI-compatible format)
	Messages []ChatMessage `json:"messages"`

	// Model Name of the generator model from models_dir/generators/
	Model string `json:"model"`

	// Stream If true, partial message deltas will be sent as SSE events
	Stream bool `json:"stream,omitempty,omitzero"`

	// Temperature Sampling temperature (0.0 = deterministic, higher = more random)
	Temperature float32 `json:"temperature,omitempty,omitzero"`

	// TopK Top-k sampling (Termite extension, not in OpenAI API)
	TopK int `json:"top_k,omitempty,omitzero"`

	// TopP Nucleus sampling probability
	TopP float32 `json:"top_p,omitempty,omitzero"`
}

// GenerateResponse OpenAI-compatible chat completion response
type GenerateResponse struct {
	// Choices List of completion choices (currently always 1)
	Choices []GenerateChoice `json:"choices"`

	// Created Unix timestamp (seconds) when the completion was created
	Created int `json:"created"`

	// Id A unique identifier for the chat completion
	Id string `json:"id"`

	// Model Model used for generation
	Model string `json:"model"`

	// Object The object type, always "chat.completion"
	Object GenerateResponseObject `json:"object"`
	Usage  GenerateUsage          `json:"usage"`
}

// GenerateResponseObject The object type, always "chat.completion"
type GenerateResponseObject string

// GenerateUsage defines model for GenerateUsage.
type GenerateUsage struct {
	// CompletionTokens Number of tokens in the completion
	CompletionTokens int `json:"completion_tokens"`

	// PromptTokens Number of tokens in the prompt
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens Total tokens used (prompt + completion)
	TotalTokens int `json:"total_tokens"`
}

// ImageURL Image URL or data URI
type ImageURL struct {
	// Url URL or data URI (data:image/png;base64,...)
	Url string `json:"url"`
}

// ImageURLContentPart Image content for embedding (OpenAI-compatible format)
type ImageURLContentPart struct {
	// ImageUrl Image URL or data URI
	ImageUrl ImageURL                `json:"image_url"`
	Type     ImageURLContentPartType `json:"type"`
}

// ImageURLContentPartType defines model for ImageURLContentPart.Type.
type ImageURLContentPartType string

// ModelsResponse defines model for ModelsResponse.
type ModelsResponse struct {
	// Chunkers Available chunking models (always includes "fixed")
	Chunkers []string `json:"chunkers"`

	// Embedders Available embedding models from models_dir/embedders/
	Embedders []string `json:"embedders"`

	// Extractors Available GLiNER extractor models (zero-shot recognition with custom labels)
	Extractors []string `json:"extractors,omitempty,omitzero"`

	// Generators Available generator/LLM models from models_dir/generators/
	Generators []string `json:"generators"`

	// RecognizerInfo Detailed information about recognizer models including capabilities.
	// Map of model name to model info. Use this to determine what capabilities
	// each recognizer supports (labels, zeroshot, relations, answers).
	RecognizerInfo map[string]RecognizerModelInfo `json:"recognizer_info,omitempty,omitzero"`

	// Recognizers Available recognizer models from models_dir/recognizers/
	Recognizers []string `json:"recognizers"`

	// Rerankers Available reranking models
	Rerankers []string `json:"rerankers"`

	// Rewriters Available Seq2Seq rewriter models from models_dir/rewriters/
	Rewriters []string `json:"rewriters"`
}

// RecognizeEntity defines model for RecognizeEntity.
type RecognizeEntity struct {
	// End Character offset where entity ends (exclusive)
	End int `json:"end"`

	// Label Entity type (PER, ORG, LOC, MISC)
	Label string `json:"label"`

	// Score Confidence score (0.0 to 1.0)
	Score float32 `json:"score"`

	// Start Character offset where entity begins
	Start int `json:"start"`

	// Text The entity text
	Text string `json:"text"`
}

// RecognizeRequest defines model for RecognizeRequest.
type RecognizeRequest struct {
	// Labels Custom entity labels to extract (GLiNER models only).
	// When using a GLiNER model, you can specify any entity types to extract,
	// enabling zero-shot NER without model retraining.
	// If not provided, the model's default labels are used.
	Labels []string `json:"labels,omitempty,omitzero"`

	// Model Name of recognizer model from models_dir/recognizers/
	Model string `json:"model"`

	// Texts Texts to extract entities from
	Texts []string `json:"texts"`
}

// RecognizeResponse defines model for RecognizeResponse.
type RecognizeResponse struct {
	// Entities Array of entity arrays (one per input text)
	Entities [][]RecognizeEntity `json:"entities"`

	// Model Name of model used for NER
	Model string `json:"model"`
}

// RecognizerCapability Capability that a recognizer model supports:
// - labels: Entity extraction (NER) - extracts labeled spans like PER, ORG, LOC
// - zeroshot: Supports arbitrary labels at inference time (GLiNER models)
// - relations: Relation extraction between entities (GLiNER multitask, REBEL)
// - answers: Extractive question answering (GLiNER multitask)
type RecognizerCapability string

// RecognizerModelInfo Detailed information about a recognizer model
type RecognizerModelInfo struct {
	// Capabilities List of capabilities this recognizer model supports
	Capabilities []RecognizerCapability `json:"capabilities,omitempty,omitzero"`
}

// RerankRequest defines model for RerankRequest.
type RerankRequest struct {
	// Model Name of reranking model from models_dir/rerankers/
	Model string `json:"model"`

	// Prompts Pre-rendered document texts to rerank. The client is responsible for extracting
	// and rendering document fields/templates before calling this endpoint.
	Prompts []string `json:"prompts"`

	// Query Search query for relevance scoring
	Query string `json:"query"`
}

// RerankResponse defines model for RerankResponse.
type RerankResponse struct {
	// Model Name of model used for reranking
	Model string `json:"model"`

	// Scores Relevance scores (one per prompt, same order as input)
	Scores []float32 `json:"scores"`
}

// RewriteRequest defines model for RewriteRequest.
type RewriteRequest struct {
	// Inputs Input texts to rewrite/transform
	Inputs []string `json:"inputs"`

	// Model Name of Seq2Seq rewriter model from models_dir/rewriters/
	Model string `json:"model"`
}

// RewriteResponse defines model for RewriteResponse.
type RewriteResponse struct {
	// Model Name of model used for rewriting
	Model string `json:"model"`

	// Texts Rewritten texts (array of arrays, one per input, multiple per beam)
	Texts [][]string `json:"texts"`
}

// Role The role of a message sender in a conversation
type Role string

// TextContentPart Text content for embedding
type TextContentPart struct {
	// Text Text content to embed
	Text string              `json:"text"`
	Type TextContentPartType `json:"type"`
}

// TextContentPartType defines model for TextContentPart.Type.
type TextContentPartType string

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	// BuildTime Build timestamp
	BuildTime string `json:"build_time"`

	// GitCommit Git commit hash
	GitCommit string `json:"git_commit"`

	// GoVersion Go runtime version
	GoVersion string `json:"go_version"`

	// Version Termite version
	Version string `json:"version"`
}

// ChunkTextJSONRequestBody defines body for ChunkText for application/json ContentType.
type ChunkTextJSONRequestBody = ChunkRequest

// GenerateEmbeddingsJSONRequestBody defines body for GenerateEmbeddings for application/json ContentType.
type GenerateEmbeddingsJSONRequestBody = EmbedRequest

// GenerateContentJSONRequestBody defines body for GenerateContent for application/json ContentType.
type GenerateContentJSONRequestBody = GenerateRequest

// RecognizeEntitiesJSONRequestBody defines body for RecognizeEntities for application/json ContentType.
type RecognizeEntitiesJSONRequestBody = RecognizeRequest

// RerankPromptsJSONRequestBody defines body for RerankPrompts for application/json ContentType.
type RerankPromptsJSONRequestBody = RerankRequest

// RewriteTextJSONRequestBody defines body for RewriteText for application/json ContentType.
type RewriteTextJSONRequestBody = RewriteRequest

// AsTextContentPart returns the union data inside the ContentPart as a TextContentPart
func (t ContentPart) AsTextContentPart() (TextContentPart, error) {
	var body TextContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContentPart overwrites any union data inside the ContentPart as the provided TextContentPart
func (t *ContentPart) FromTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContentPart performs a merge with any union data inside the ContentPart, using the provided TextContentPart
func (t *ContentPart) MergeTextContentPart(v TextContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsImageURLContentPart returns the union data inside the ContentPart as a ImageURLContentPart
func (t ContentPart) AsImageURLContentPart() (ImageURLContentPart, error) {
	var body ImageURLContentPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageURLContentPart overwrites any union data inside the ContentPart as the provided ImageURLContentPart
func (t *ContentPart) FromImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageURLContentPart performs a merge with any union data inside the ContentPart, using the provided ImageURLContentPart
func (t *ContentPart) MergeImageURLContentPart(v ImageURLContentPart) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEmbedRequestInput0 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput0
func (t EmbedRequest_Input) AsEmbedRequestInput0() (EmbedRequestInput0, error) {
	var body EmbedRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput0 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput0
func (t *EmbedRequest_Input) FromEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput0 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput0
func (t *EmbedRequest_Input) MergeEmbedRequestInput0(v EmbedRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput1 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput1
func (t EmbedRequest_Input) AsEmbedRequestInput1() (EmbedRequestInput1, error) {
	var body EmbedRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput1 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput1
func (t *EmbedRequest_Input) FromEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput1 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput1
func (t *EmbedRequest_Input) MergeEmbedRequestInput1(v EmbedRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbedRequestInput2 returns the union data inside the EmbedRequest_Input as a EmbedRequestInput2
func (t EmbedRequest_Input) AsEmbedRequestInput2() (EmbedRequestInput2, error) {
	var body EmbedRequestInput2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbedRequestInput2 overwrites any union data inside the EmbedRequest_Input as the provided EmbedRequestInput2
func (t *EmbedRequest_Input) FromEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbedRequestInput2 performs a merge with any union data inside the EmbedRequest_Input, using the provided EmbedRequestInput2
func (t *EmbedRequest_Input) MergeEmbedRequestInput2(v EmbedRequestInput2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EmbedRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Chunk text into smaller segments
	// (POST /chunk)
	ChunkText(w http.ResponseWriter, r *http.Request)
	// Generate embeddings
	// (POST /embed)
	GenerateEmbeddings(w http.ResponseWriter, r *http.Request)
	// Generate text using LLM (OpenAI-compatible)
	// (POST /generate)
	GenerateContent(w http.ResponseWriter, r *http.Request)
	// List available models
	// (GET /models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// Recognize named entities
	// (POST /recognize)
	RecognizeEntities(w http.ResponseWriter, r *http.Request)
	// Rerank prompts by relevance
	// (POST /rerank)
	RerankPrompts(w http.ResponseWriter, r *http.Request)
	// Rewrite text using Seq2Seq models
	// (POST /rewrite)
	RewriteText(w http.ResponseWriter, r *http.Request)
	// Get version information
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChunkText operation middleware
func (siw *ServerInterfaceWrapper) ChunkText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChunkText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateEmbeddings operation middleware
func (siw *ServerInterfaceWrapper) GenerateEmbeddings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateEmbeddings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateContent operation middleware
func (siw *ServerInterfaceWrapper) GenerateContent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateContent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecognizeEntities operation middleware
func (siw *ServerInterfaceWrapper) RecognizeEntities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecognizeEntities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RerankPrompts operation middleware
func (siw *ServerInterfaceWrapper) RerankPrompts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RerankPrompts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RewriteText operation middleware
func (siw *ServerInterfaceWrapper) RewriteText(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RewriteText(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/chunk", wrapper.ChunkText)
	m.HandleFunc("POST "+options.BaseURL+"/embed", wrapper.GenerateEmbeddings)
	m.HandleFunc("POST "+options.BaseURL+"/generate", wrapper.GenerateContent)
	m.HandleFunc("GET "+options.BaseURL+"/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/recognize", wrapper.RecognizeEntities)
	m.HandleFunc("POST "+options.BaseURL+"/rerank", wrapper.RerankPrompts)
	m.HandleFunc("POST "+options.BaseURL+"/rewrite", wrapper.RewriteText)
	m.HandleFunc("GET "+options.BaseURL+"/version", wrapper.GetVersion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9D28bt7Io/lX4U39A7N6VLNtJmuqhuHAcJ8f32omP7Zz2vCiwqV1KYr1LbkiubbXw",
	"++wPnCG5/2W5bXoO3i0QINYuOSSHw/nP2V8HscxyKZgwejD5daDjJcso/Hm4pOaUaU0XzP7MlcyZMpzB",
	"y1gKw4SxfyZMx4rnhksxmAwul4xk2Iv4RtHArHI2mAy0UVwsBg/RQMkUoP7/is0Hk8E3O+U0dtwcds5t",
	"mwfbmH0puGLJYPIJO0Zh/M8Btpz9zGJjYR8uC3HTntkBie0LIufEsHtD7rhZklxqbt8TLuZSZdT+PRpE",
	"jdUykVzFS6raQA+XVNHYMFWFRKTiCy5o6gZaMsXc4Ewkmmyx+zgtNL9l2yVuuDBswZRdAE/aA12wLwUT",
	"MSOiyGZMwSqWHurWOCK7EdmLyGg06oAZDe6HCzl0TwsuzP6eHUgbqswftDKApTvXY9t2Uwp27aWTxt7z",
	"ZOCA1aYelfvTSw6HUsz5omOV8LxQsPFkLhVOiYsFsSMzbTQxklwylXHDyMHZ8WgqLpdcE64JJZpnecrn",
	"nCV2EXO+ABB2Y/52eXlmm5MhSfh8zpQmcyUzeDcv0pTAtJjCCUzF3ZLHS8JFnBYJ0yRX8pYnTBHNUhbD",
	"5KhISEzjpZ1bXJ32aCpaFJvR+ytYicY1z2mRmsHkxThqIOCU3vOsyCpkhd3sqhUzhbKw2T3Ncntgbf/2",
	"/mYyYWltnMGc3zO7Wz1bbtcAvewwhWYjcsTNkinyDDo+AzQCchkx8oaJ4Yxqi2TXOSJSEepACJoxRC78",
	"1jsxolbv/GpfPeyMqksIU2vxJHnLVErzKxjwMby9D/hy3XK7JuxKZszcMSYcKh9HoGY5VdRIVUfiVMDO",
	"NnBoD17oAIiCFQXc1BbrQLTWaqhaMNO91NZaL6FxlfPgMnPmjkt9hZ1LNEvF9FKmSW2w8ehF1HUiE2B1",
	"oQ+s8sP79z+5HSZb49F4uDsab1dHBmDIxe02p5JWWApOHlhKN4c4x+PeKeoc61gnrKpcpp/l2b0zso20",
	"QclSUikWJJFxkTFhiFlSQwRjCRzIGSM6T7khXBhJdEbT1G+BHo1GjzJQmNXnfgzoXAoNcjnM7NeB5Tns",
	"asnNYDKnqWbRwDOWT1XJuGv33UqucV2ujD0ywhqBBXKlDc7cTvwhqoH63oHarYP6vhuWZrEUSQXY58CS",
	"3GF/aLLHypqae/TjkgEnUkwXqSF3VBPN1C1LkMVAzxLRMylTRoUdocpua3qHUnQVtI7AErhhmd6IqgYl",
	"zVILq8Fy60K7xlxpbAqapivLYhOyldGVE0a4FifhWEL4nMxpms5ofENkHBdKsWR7E67ZILCwOpxfVEF0",
	"J9mFo1XfHprzq0J1rO/j+YnXfLxIZtmMJQkXi50gWex+8ZjV5r80Jp/s7KQypulSajN5NX41HlT4RaF4",
	"F6O0KLGUmSsuFTerGvv6NJBC3Fv1KqWDaLCQdpX1Gb/G/sT3J1JZsW4ZGu5RKqmdPaqjErrRlCTMroDo",
	"nMVWvVB6NBVvYaoTcu3mdG2FoP8xwR7XTidz/d1MgXlc08LI65GVCB53RnGmCRP4P6h3dnJW0yg0q55U",
	"ekt5SmcpI268/8ARpiKW2YwL1J+AW+kiz6Uy2BvWCGN++61Dhf72W7KVsNxiRQoyK3iaEEMXensyFUNy",
	"vZDXZEjOCsXIO2n1cqZAGmzR9I6udDmViByefSRSpKuI6FTeMW22AYLdFAsDJMZ5IQzPGNlydKrJ0A72",
	"wxT2LvpwfjkdRGROtQn971Nqu7+Tpyc/kZ9ODjr63qc0+unkwHa9PPu4c/jxzcHO4dnHbVzpG8CN/vZb",
	"XBEgngzJQWHkMGGGxYbMWA2rW26ncAJxkcAM3v/j+M3xAbHQybuzj/hOKpalAC636tGhVOz0xB7u+MOF",
	"wwYc99kKEIAQTV7gkuQiZXbKZMs3+unkwI2Kbd5KFbOAWlzQEZ6jsKJPiD27fMAF/rGQ08FnC+JSrTyd",
	"aCRsi4KSKA2qtFVQE7vmAG9i8gJ/4Dv/K4xwpphlY+/OPkbAuWA4S+WHDk0BLKCr0RtxBRNz6KNxzFKG",
	"+vS0pvJ+KqeHB93ObRCFibmH+BdygMDa22pXg407y+dKs7jw3GWdPKDCzNPVcCGvUj6j8ysdK2oVzyuZ",
	"M2G55iECvHDwSoXkhrH8iqb8ltV1zHFLwfybvEMlxEhie3mdyzIqKyoEyVgm1YrQubUOU6qNJTiy9SFN",
	"aUaHdtrU8FnKtkdTcYqdqWJAA9bCjlEkCQcQwRgr0BNviMk54YLGht9ysxpNxUcNzCCpGGrACqeDF9l0",
	"QLZekIyLwjC9bfd5d2mf7ZKlLBQ8GNvfgt0y5YaNCKMLO3lkvnaiPy6ZIJqBfoY9pCIy48awJPI4sMtw",
	"0wYA6YpYjmd1lCIHvlkdxcrclC1ovCIztqS3XKrtUZ26Bi+yLqmTysVTSSGVi0WDEtzWgy0oBUh1Ya68",
	"XVtXxDewCwOIClMORjJNLQdORlNxkCTcSbHw9o7bI8rIl4IVLCFFbrFs5wUPrjT/hY2m4gKxPwbpWIiU",
	"WyGVlLyxgbvnnbYovb9C3F/hnj11mW6nPfG3qF7zrEgNFUwWOl15wgHyhQlbrVQxq/YkEYjAlNkToljM",
	"hPGqGIp+riuEcnL+kVj+aCe2vQkyyAeRrgibzy0zvWVW8AtSHnMLXUgx/IUp2UDcfh/icIlX2WwzpDmM",
	"bHFBTl9vO1Me5usWhbjsxhHNcyUdmnpRhCfOI2kjrARLShCa3HJtZ4iDDp0+7OY9FQV4KVEV0VYXwW2x",
	"1KjhMFuF2bAsl4oqbpF9HzOW4EJuaVpYov1RqhtL/lIsNE8YaRGgM9EFGy4U5QJdRUbJtEnO4+9f9m1M",
	"eUyeSs5VLxZAQTrp4QkV4i13zR1b+25epGlEBLsr4dpds+T2YrxPLlDxJh9FqdmAlD1nRq2GB8Dpl4wm",
	"TPXvJQ72CJ33zX9ajMf7jIwbuN0d9zuurrRR1LCFtz0C+zpr+ICLzGoDwPcH0SClv6wG0WAmC5GwpGLe",
	"lFy8vjdnTA3rKr8beAUuJMUTpkfklOa64teCfTNLxlWrVylchbQsGckyozmcQrttDoXlOOhEk1U2Afrc",
	"8bzy5AcnL/0GTOqykmzZPypiL6rJvO0WPNyS8YRYjDWgSEESllGRRK670wZ4kjLQpYEEvaNvaW1xv5Yp",
	"7sR0UF06rgb4i9cuSvG8RTXJqTL2WOSKlbOF9nXBHRF2y0STp7qlkK2cC1GVCjBX4DwgBzXJ+L1dJWLO",
	"shJYvGMIHE+VphkjuWwxgl8HswUbgndnyMTwdnf0YjAJdBcvpbhZDSZIgF3uLBzlKuEdXv3XVDOScMVi",
	"Yxmj5USUi9JjoIuZf8stOXpLkYLpwnVsSVX7hcyVzNAg+LUc9GEHTXKm9I5Vto+8gR6cd6VZUusW3La2",
	"V92T0d9JMUXLXufwa6NusVwI/kvZEX6Dcvlo1zvFje94wb7sXbAvxD9t9p6KNxUb/P/sjAxidMe3syrn",
	"LafkludMbY/s2bHnWTMTgQEGBrIZctFw84KM81y2qVW2xulSMt0ZaBPJCdcmqEIlG3Lta0eqU+e/XDLN",
	"OlRmnmUs4dSwdIUny1MXxo4iQm8lB0oBp8PQcXWSUsNEHBiem5FeyiK1MtrES2KWUjM4j2GnKmRIttho",
	"MbKWQOtkTQd2xpurUmSrxsbscE299FPH+Y0Gccrz4S03EMkY5nbW+3tPsxYdPq4Mz5gszGOGnFcGwP1h",
	"JLmj3ICspV56gy9a2lkbFrngk12VUxRse9t5rQG2P9ZoXe9m+D8aW5K4WUakor6fezmNmhSETCzXdG0r",
	"ysRz8o4adkdX5BLfNUl8f9xJ1Hr/KlYsYcJwmuon29P7pf1UgdJ0c3r/ZI9P01rgZ1SZzhg0vkZBBF7A",
	"IjU8kwlNS1cm2QJfsVSEZ3QBUWIp2Ic5uNzXreeS3ZvqBB6i9e2PLfiP5ye1Pp8fogEw7d6QCBd50bG6",
	"Y/s4rNBIXNCIXJQeQcWYox0NguOCi0XK0DWOmzgh19PBkqWpJHdSpcl0cG0b1r3o2FRPwM8DjZH2XI/P",
	"9S5VnGuyVWJ82wL4dQqbOB1YarbQERT+ZZ85+A8RqTWFrbFkgO0rPye2oftrOkiooRN4u5OLxf+yx//l",
	"82g0Gk0HDw92pnXeUVn6wCr/8ZILMCKVFdOW5EpSaKQItHBJtmY0vrmjKiEVDt1xbNbHLBy2e6FtzMF6",
	"h6kcgsZm1Q6C3t44cFI7BI15fO4PoLy3OpmLMHj54eRgJcLcEC81vtTF+9t4UYWIqalbc0YVrBV6dQ0J",
	"HDl7pubcuAkBpu4NSZlYmGVHTKrBtXxMBk9vF+9yp74zDBiYkx5MPn0aj8a7e/vRcDwaP3/xMhqPxt+9",
	"+v5zZJ/v7T+H5y9efmefv/r+cyUe18ZOKzZXHaiXYEpWeQvKqiZbUjCISCOmENc1egl/PBYjbkveDcNv",
	"qJ6A+8Ky9jDJpxJIz8ZVMNO5e0phBkEDn/5xfa7Q2qdqPToFBNI16lsuuF6eM6ot2OYo+JzcLVdkwYRz",
	"sBNtZJ5DONFb1faJNaoDKUuZXsU0Bc3Ve8nnPDVgA80LAX4yaNFper/DwdjhUvK4I39tDrO+UmHa65hJ",
	"bYkP9gAl7L5L/CXsHpkH1ySGkb2tl3JtOnOjUrnIlZx10PqJXBD7is54ys2qmqFm9asQaLPGqguNiSJN",
	"Lcnb/61Z4HlK20Qs8/rWLdxj0acBthKyABEluKiB1y56KXemM0vvwihGM3uwK/TistwuLo7ALDfEytTt",
	"VtITorx+1jdZHuZuIKV0BWkUo4YlFQHXytVr0V9gEO0sI8RExaMUL6kZOTWcSzHC7JDPG2XDOWjlJCuh",
	"d4eNRzeh74wkLDV0Uxy+gcYP0R90spqI7iE8nOK6Fb7xi6iTGTwOugZkm3nCa5NVb66rvGEiAMG59B6+",
	"35j72ruw35aa6w4VS/7VSbp+Gb02Rkbvu9LT9l687LVzMSvNyLDKqtyFjh0uYESD7kwNvWVKIwfyzcjW",
	"h5yJg+OKx8PZM5urppW86s1Vi6pi6pYn+zTT8L6hmi5YltHh/nB3NuSdG45noIZvl/LVkHRzArQNSjqH",
	"iIp2sZTU0DLcp+25oJoExq07M6cMy3I74ULVFeLd5rgXdiXgNCh7QC4g+QGyClRm+YnhcUSWfLFkivxA",
	"MqkYUVQkMmtkC34XbaIJyvzq5pFc0EuZD2+I9pPbCqlJ94YJzaWIvIseiYccnB13Z37b0fL1OHhfxCkr",
	"dDlcRUcYbJT/2KVahmOw/qyWlkF9Uu1DYYUaKYUaUb7vGqHd7YWsAHFtyZaL+6Qrr/nsbnz8Gprhennf",
	"yD4T/B5cVdrQLCdbmHiot9FfCOn45VzvqCalUC4jUd+Nn+/u7T/v5kZdmf8HpBD8S8EIB3/UnLv0MUz/",
	"r2G5dtrtuzjL0yGdxbt7+13nfTMzplTEOrOmgz7Tljb4jtg+QUedNvWd6aBiBzTeder2xVNU14/diuuG",
	"upMfbN2p+Ngnhv0iamKsO4fciS7epKJOJpErmeXmyVCxWw/bMTTtBXhp33pgmEmKsMh/VKbaxdAaWK9P",
	"POpAUWMqXWj3LssO+8u+IZAiqsBCIB/Pj1v8pj+vtOxEtnqddvWs2O5m/B+vP5zfjf/73UJukpXd50nu",
	"cs72LLqqyFa8yOt0lYZH13svHztXAf2BcZaGTAnkUeMF3kadPUoEYHi7KnWaogMDhh08M6QfxM04omND",
	"4abNFFObp4Ptuh/WJzxjvHWY2UNlnOMG3JVW+BY0He4+LYgT3IbrZs2aMdPNnI/dkafWsyF/Nfxinjjt",
	"e6MoeNrWzfvdCX9/dE5C44D1X5iSQ72UEOIJkVbIDYkLbWRGUjpjqW5swiLlgimc/SDyPwH9huqbpy2h",
	"VIvXLSG02jk5Oe1Df4+G/amtYnOxGqL2OXTvnhrz84HqKy7mcl2GylozLYCBQ3VsQbUyVN4wQ3kKeQ2l",
	"q4nOXGDO9S+TGHy0MKY56p+c6dFUnNK8HjyGXD9MeBNzOSIfIT2Fg6XmtXZG7kCVqYCaCkbjZXXkkFm+",
	"hcQSEUtWlqoiolgK89URoULfMaW322kV9gRD+FUwhddAyuHs7iHYweeHDlLrbx4N/DQGdr/cPAbRwE2k",
	"Cg8peSNYnzvN/0riwjoqbu9Xk4SrGRANHlJDUzRIrEmVwlN8UFvLE6nZZWusn3s9iaPN4TyY4e3eMHvy",
	"gXLpG+um0JfV0UaizwVpCI+UiqF5ERhXmn1ZDMHRwaUYVhTqJ0y966qNXUYVq1XxUmN4dcKpYqFL8AZu",
	"cSSMy0pvXYhed2NYzuea+evBDGB03XyupOd1usbtkegIXCA8255snR2dR+TD+buInHw4jMjp8cVhXUM7",
	"Ozrv9HTEUrGe68B4+RBaoHPBSNK+a/j995u4DyCz5amomrEFFzWyHz/tWrWD465Kl8j4L7kU5CLj1Wjh",
	"uquCfg/8OuCm9cBjby3l9Pr1HKNrowTVADd1bAU5BKhLkC2nW7iTKEW6Cmn7hbbcgpJqk4isZEFiKtwl",
	"qhWhYhUws8pZFXo0FUzQGfhTSlXFwrIqihWAKMAUMwrz5UZT4TK13FVtl+0N7Z7pkHvpFgJpzBqyauuc",
	"ImdKg50HSrpYoWaeFGCYJtSwp3G3R7yHTbGwsVRoCYX2TNi90d1XXmv7CDvAGfLSOi5K8iR3mFVt3I0l",
	"a0ThdadjEY8IB6P2sACyEnL0O9iot/hx+o+QdJ8h4te0LmCNhAeTaAWr7eDdoeqNdDrHpX973NqTR1Z3",
	"/Lzv4p19sWmPgrUoVIde7Vl1cIDwDi8S0ja5eg0QcofwaE2IEwiOwCA8+v7ofJsM/SONTVlCdE6FJim/",
	"YaQmOSw4r3hNynwlqmbcKKoCP6LVuy94rbDGliBdNKiAE3Lu/qxOzhcHCAchgPC6ZkTOj14fnQAwp0NO",
	"yJGDcAvp+NqVhLAvwdRvwthGRuMs84011Y6D3WU6dMTTek2H9ja2fcA1ZbjXEVxphQZEL33U+UqHbh09",
	"8YhVCbeLpXSQvNXJ+qNbj/HpmgrcwaZ91nMrtaShG3fm/cos7+LVZ8p2FwlTLKmUIPAcHCGPCFTxSDlc",
	"BNPese+9S4HSxWIqqEgIAuTVogZzztJE7xiW5Sk1TJMZm1tlK6ZpGlJCmUhyyYVpScxjYVBAwo1jSZop",
	"cuhyewOXt9wjMi9EQu3YNIVCCU+SqV8KplZdFXmoipcE3sLKFUvZLfW6YzPtpzlNQvM85XE4gpuxWZxL",
	"uYef15Ben7R6mhAIpNirRuuutJ8qKlhF4OHEI7z84K6baxSDNQn41BytHny5CXajCUyg9Umuui/LtXIq",
	"AMyOUVRoO+s6tV7ax5bKbdt3TGVUTMjfWJrKiCzlHSiGK1n85x+q5nWbrxtary3jdTPKdOhai+k/iiIt",
	"uB6K7FFDcQqGCbdxW9QrZqiRRaSmkUUoSK3CaZ/NGM269bNHd+r3Kp8uBaNt4ymZAnJoCL5r4LRWM4bM",
	"lpC8UE2zW2nDMghrgRZPteba0FqORrmWZjZ5dz2bzthDS8SvKYjTTBjv3NZGqKFRyWZ9lKG37M0/mNJc",
	"in7ChOIUcN+i4yoVFq7w4eDaEdob7z0fjneHuy8ud8eT/fFkPP7fXctacHMVyyzrKkTzjkNoN+OGLKle",
	"1uBjSPd5J0h5dYvL6gApiXLlMHybWn6I3B3tvRiNu8D2wvTJDl0Ab3dH4y5wjW0qu1bwEVWRX1tW1042",
	"L3L4sE95neOvooB/FQXsp5ee6gldSbmLVgE+YH3hLhvegdYteknZLUt/b1WHEwACu7R6PDnvMWgXAKTT",
	"ftlsIrUbaBCfinoQdsvUzJLMiiAeSpmUsFmxAAUCut9RLDnoE85LbuIatFjTZqusTRWDTjTtna4sjNXy",
	"8PgTQPaIPPPdsD5hLFOp+C94oV/LlEXk2c9aimc+n7SITWFNqf+6+PA+Is9SuZhnBt9iUUM2n/MYDKkb",
	"tvoBKgqQnHKlI/JMSJn7OogpE2ZUQVll+j+j9xBhD6KB7VZHW6Xxo6jruf/WLtAVx0zrqxu2uupMWfrx",
	"gmATuzBy/KZyB+yGrbSx1p5eCUPvcYUsVsyQVMqbIh+RtzRNdajoc/DjxdXB4eHRxcXVfx/98+r4DWHi",
	"lispwJa8pYpDyIaHe7P1co8rWaghTmZ4w1ZD3qlfeGuzg8fuV/MnfDt/o/SZ3h/RjP4iBb3To1hmz4hU",
	"dqt9mbHvx+MxbuMpF8cf6sGJZudBNMi4OMFLEJPdLoMLMHVV4r8b+Q6h5R783g24ODo8P7qs7MNv2AQc",
	"pLIXnRYl0zokBHUlGrrSMrhKaIuHCY+VK9axIpVLoE9ae9e0YZQhzqgzH41daZ0+epfrSGBs8eJk5/Lk",
	"Asa+2Le8Q2A5LB1qLkwgvRZaHPx4ARWuQmGVmKYlKXXc+HqUk29YM6p95rHCz5Ula91VN5EbljpXnWtL",
	"bFu4rb1zfIaFUFIubkgi76DOgobr7izLzSqyfaC9KxblIFi1iOWG5IrfWivawuFzMktlfHPlHl7xHItB",
	"qoJtj+r2t/vTna44EaP6k93v90bj0d7oiVk8Hhk5NctNkWHbklyxOb9nvipMyiY7O1AgQu/bvz6en7SQ",
	"AmNUkTIibyudC80InWmZFoa5to457XzU1rhPqKE729gJR7FdZkV8w8wOzsf3yFZD97zIYYN2mviswrTs",
	"qtXhaXhs7eOjp+i17VEra1OSBlFUQJL+7t531vIYjXdeRWR3XPn7u73R7kv4tbsXEbv7uy9f4e+XEdl9",
	"+f1o78Vz93u7M1vdE6+/hn/l0oBrM99vJ4m7K+5237lI+C1PCpqGo0Bk7nICILblYVarNo1BOvDM6gC7",
	"fZWCwuw0/4VdzVaG1Se2O37+6sV3L8e9pYNsP0u1HpCrV4RlvwgCrIXuA7wwufEjtgYX5uVzP2FMAUx4",
	"hqny9cse4+ev+uYJ/cgdT8xyZ8n4Ygnzy/k95JvhdeFwEUExu6x6SVMEvg6jbW768OD0VHfPhmLms2Vx",
	"VvICpx1EmGMKJUf1ZGdnwc2ymFl+4xTyZLbjqnO0c7C8GYEVrFx5DQhYIesvw09QlVaF0siuQvbpSVl1",
	"ayq++Yb8uKTgp3eAq+U/XeRae6lyUoGOVRvDDCoq0MHZMYTfvv22rOzyLmS0fPvthIBXB+pnlde6tw5P",
	"js+2W4mNCAg6+IovFsIFy6gwPC7TN2E+1RLQvu71EAjWV69FeKEMjIVV+qIVGzrPvBP84MDHQr9uJu9p",
	"xhIfUawUhbGAXASOYMheR0SqBRX8F593ZrGIBxgrvbN7U1neufdaAoa8sxhNZsxf8F5bnzMZwnxlvlDk",
	"wg3VJ8zEIyw041kJXDilhkFNtZRRKyAM8eSINDjicieRsd4JsjjQC4OwykfNumgmpoKoQljLXiQ0lYJB",
	"KfayshIVBM8BidNCG6aAWE6Awsr9a1CaZYzs3jAFqt3ZsSvKxkQMiYDDDjK83qE5xzzY61ItrzkhoWcg",
	"pbL8sieA84N3JOc5S7nAUaqk4gNwwK8ze1RY4knmS0FTbla2yyETRtEUzEAXg2TqFuI7sZJak4Rb6Tcr",
	"DEuIkAkOdGZFVrwa5or55rXTB/nnriRVyugt08TqoraFosGy3HZb9pbBTSi3g9+QrnOJlIgZ1ZYCq0ep",
	"VtzJF7ruLemEkA7OjgHMZvvijyX6WQlWMoZ5vObCquuh2lgE1rJfyWnJQJwO7xgJAsTk97BcAGhfk0rl",
	"vZ+BLuzmD1FklCxI5zRmDhIEdarzglT+cCNAk63r3jsB19v2DFjVDYG5tPvDgBQL8KNmulHcwnkXtq5/",
	"U10RV0Hk2uHCntdDqqFGL0HEILVGBAhxiGhUzCjObmkakVuurQaiecZTqoCeEes1dtwknLcl0w2HqVWa",
	"eZv8R5XCKjDIG0dnKwvsoLesWG9tMIR1iB/CsDD2hlj7lVxenviSlFB2HFu+dZIB5l6za5v1tHygaU55",
	"Gs5SECWbrqF6sDoWUqlXhhD/Xlj29EsQngf1KrmWar5gk7IoJp+XqK7Qr+1ei+EDy3OhYrLlYvZLKpLU",
	"GiCcpUklMQUzRlIeMxcK8VpNmpJzq19pcs6wFH5LxSllSsoWFByUhhv8skH56ZRBJYwwuN2lab6ku3CH",
	"DC3RwWSwPxqP9gfRINhVuPNgjUrd5Z7JU27NALvSjq8iONGqvRCoaw2NyyFeZTp1RIsUAARf1qNr0zrW",
	"MWp9qwS+1GDK0u74mRDb+KOvjvZDuHxiH7+lGtWm2lVWPw2gq9NwnNoaUiju6JlM9WAPyek6Xl8JCtdP",
	"2pNPDHEn0/46R80KTFc4kdU6upY37/myzSPoxsBbGG7mzKRZ+s/qWLSYSrDQb5UrTG5/XV9f/6ytoPt1",
	"KkitgFPPxzWAgUbYGIdBFisIsY9gaQjAbVLkX9W+nmKbvBiPw8v6Z2TwbXgZPtyCgKdTYf8N7OuHqXiA",
	"VcA5DObgceK/63CJQQ5n+r6Wyapx3b+SUbLzs6u+gKGAjb4z4TMhHuohFmuEwwMU3nAq98bjP3psF4KF",
	"wbuCxECWCdEFuA/nRZqCA+H5HzgTLKDTMYNjcUtTnnivgx33xZ8zrlOJna3HXMNooIsso2rlSaOD/2m2",
	"yODGvW2O+lg/F/V3WbUrp1TRoZ3DolrZDXlq2lDptf8yVlDGua4UCnMWHOiLz3RdTXSKEHpw702EmWNw",
	"fT7RhLuwbPs2Y8W+dJl/AKOiArZZeqMg/VpeWC1kWla9dOUQrZWFq8AeFSvESCj4U/m+Q2U23iIcQnXP",
	"zClW3gPXuqy3PSEHMbhAq7XYnDZSrr8JB7TkeleLU+cXueW0VG0dimoqMNazrVTrA4SFikNftXZfV1XR",
	"/np+G5XwQ1356xTw67hmu/07ZWGl0j4EMeJqLX0Kn3dJCuQ2LJkKp+PAdsxTcIVhuVaolaRYUoiECgNJ",
	"9f5ANG0x+ziESULyU0jNgfsSlmocQWERb/d5kwrjk7FhZoh1RK6DdaeZ4tZGdsWrnK0XkUxqQ0IQdLsF",
	"zbLR6wlYhKGABPKCyu1CYBUVk7+qFyAdW6qr3opuUdekrT1UpH9HzVinNQBbtI0+Ncje0lMz4XM6+FxK",
	"+Kk47az72Sal9XPrrCrbNT/QPx49J5TkS2kk5pXF1NhD09H1950cdz3eHSAL/vMa1ceLptLK/0o6UK3k",
	"6Z+sA9ULL9qx+w5VHWYjNAKnbehPG0vaZRKrFWJm0Lwjwaalh5S4rxSQ+nfRxJ6Pn3/9cV3haWkVjEIk",
	"/1YaoD8hFS6ISl8og7WB3lfxQ6NiV7n97lSKdyzLKNnfHk3FW7vpLeXOakSuwtHhkhpyGOp7aPfl1N+h",
	"i1Wu3P+Bytg335BQcRBEIDPkGk8aBuGvMccby1JfwCYML6xIPIJ6VlCUcBuXz0WsGF4ymArMScB6WCNy",
	"ROOlK13oSu5ba/TaYqlEEmjy165oDpZRd1XpSPkhLfRCkk9vPrw/+nw96tDd7CNwNvYUZXLKNopRX9YM",
	"ArLrRU2ttEEQMR5CXcoomTpRgRnHKCfcUcEX/5QFbjxZsjSfFykJycijmtgpYRWaqQ5IkE3//00HKEr8",
	"vEL5ONto78VL9xwRap9BUkVVIpdqA9l6L8UwVATcdu6FGdXLqVXNUjL8iZx9uLgknZ8VBDr0h49Mp3bk",
	"4d/I1NcGH16ucjYhTXYxHfi2CXnW5Ybo2oHWHmyCMR8TbKoo/zkdPHwuwdZQuDseg5fiWSe+Lv6fxVWg",
	"rhIxJQ1ZDlHDSq/6chjSWb+G7tKspvgnqy+tAnEPLsF3B3hep+qycWHWLrF42FNdbkTO4ZvVGm0Ga1eJ",
	"6kkOVlQ0FVJ18fNaKdDS6NqqygSoLPKXxvOnajx29P2vP/q7SpFq9zGrovIxqy0hvVLkM8BZst2nj1V0",
	"KqtNdRh3qKeVH6pbMNN1dwlJ2moxGkyzdp2oqPJp9BC7jspiRhF5f3QeEbyQWatpEjzp3teFPqp2GKvb",
	"L2bb/j3EpyAR1B6jJb1l5HrIX10TXczn/N57RFx0AQc56KvFRbb8V2/AKXCWFhrKN6ydVTVy4XwcLta2",
	"wZIacbmjLDcrTGdtb7gD/y5opAi/WS+qT3vdFH55+XizBVS+aASftfJYrRfOsAyusxpXGNVdCsQxG0kp",
	"HcOGryHZ5pcvIvL25OD90P7x+uD8Emnu5PTv70hHPkuID9dsgYoZYBV9dw6rX9mM/SfqWvL2hGtz6ssG",
	"fTWB16hM18c+tQ+3/6vM5df03zNocdJlkCEzDHTcb7WGg6HBA5hUSik8mpvl8qXKFC3HoOFsqdZXwAJ3",
	"xIwwq4yiqxTSn1RCDuX7k5NaWRmXHHd2dA7xeJiQ+2RV+AxVWelkOnD5Gx/O30FCTXXeZQcsg4LqaVkI",
	"JXQ++XBoO5+EDLTQ8T27I/+U6ga7vlVUxCx0Oz2+gH6nXMcsTfGjpgGbLXO9DCJvYrC3GFJwL39py4st",
	"/BQjfzWSQtzD9A4b3oW/FXA15y2NGXl9dH7pwuztPbOd6zzPB4firhpDt5yi+wB/X5OcKpoxw9TjMeaq",
	"l7haICeYx3Cz13mI15S3aW5sq8JNzXncYnr1SjCcfS0Xaau6059sZ7RL8XQ5Kz0zcKktf7kq/yco7tUP",
	"OP5mzT3QV0OueMlkVcR1Ymnoql3kvUlYIUmnLBZiJKEurbcmiupFEL0gOsQkrnNfdSUUy0R/ocvxygpt",
	"JlOxOwpJy248X3wF2bXPhNFTsWdNZ6gfYPXsUJplKvZH5IKJpGNN/rNgVJNrt77r8B3UhGm+wI8o6up3",
	"Hg1LmcavK7tPpeKU4SYH8meL/7JqTCoXPB79bllU0+47JJF3dWOvq/AC5BHmWNYz83LF5kx1CrN6et5T",
	"ZEirfk8QJEAg2GptJZnQwe1IxS87bZXOOXWQThykCX49e1HwhBHMZyyTpCwAqKrjW5O3lao6E/KeFYqm",
	"RDDjpJti0LkR4JuKt1IFygtC3FM7iPpmamIUPmmMxDLUPGFTcZ3y2U7oagV3fAOXQpY8XoY8x5KUHi8z",
	"1BSrFvSZK7XztURqtU7Uny5Pa5WCOtiqW7zboL9E6f8MUeoP4+8QpBZEKfVWpbzzshTcBuuEaaOs0rqb",
	"Mh1eB7Dyfr/YqDk3GsOCj4uJWCZMgZiISMLg15ALbtwjTOgtG8G9Td1l4GzgJPnmGxLy/H0u2d99j/ol",
	"rOCF9BCdzMdSf0P/8UgoNxAAqVUfFF1WO/PFO6vqA1i8VNF8qagOF68Aez43kSR8DvdbIBEp8Ve/XH0s",
	"f3WsLJdle/laiSkViwLCNi1xaqVJF9JKlCL61gc3azWvhvpLQZPhl0U9kcbbcYsmZicEPgwfL1P8QDx5",
	"zVbSqnY9j7WhCpxbmhwZQ8l/gXPA2ns04WlKY3D9qUQ/avYBgr9iXnCjRtqfLp7qdcP6coNVKO71l3T6",
	"K0KzkXiqcKYukYJCqlLzam1gplECKyKLULorgs/3Y5kwlAXtGlyjjqCx+UeoifXVjlez+lkHsl2TaiGs",
	"f43vuhFgMx539ZlBMyBK3fF97MpNJEe64R7TDs354OHzw/8NAAD//wlIKVYPnQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/s3/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../../antfly-go/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
